import type { BugSeverity, BugStatus, User } from "../types";
import { bugDexExpansionEntries, bugDexExpansionFacts } from "./bugDexExpansion.ts";

export type InsectVariant = "larva" | "beetle" | "grasshopper" | "dragonfly" | "ladybug" | "crawler";
export type TierPrestige = "Bronze" | "Silver" | "Gold" | "Platinum" | "Diamond" | "Master" | "Mythic" | "Cosmic";

export type UserTier = {
  minPoints: number;
  title: string;
  description: string;
  prestige: TierPrestige;
  prestigeLevel: string;
  color: string;
  frameColor: string;
  frameAccent: string;
  frameBackground: string;
  rewardText: string;
  bugArtId: string;
  insect: InsectVariant;
  bugSize: number;
  evolutionLevel: number;
};

export type BugDexRarity = "Gewoon" | "Zeldzaam" | "Episch" | "Legendarisch" | "Mythisch";
export type BugDexUnlockMode = "rank" | "drop";

export type BugDexEntry = {
  id: string;
  name: string;
  title: string;
  minPoints: number;
  minBugs: number;
  rarity: BugDexRarity;
  insect: InsectVariant;
  evolutionLevel: number;
  note: string;
  unlockMode?: BugDexUnlockMode;
};

export const userTiers: UserTier[] = [
  {
    minPoints: 0,
    title: "Zilvervisje Starter",
    description: "Glijdt stil door de eerste randgevallen.",
    prestige: "Bronze",
    prestigeLevel: "Bronze I",
    color: "#6f7f5f",
    frameColor: "#9b6a3c",
    frameAccent: "#d8a05f",
    frameBackground: "#fff5e7",
    rewardText: "Starter frame",
    bugArtId: "zilvervisje",
    insect: "larva",
    bugSize: 46,
    evolutionLevel: 1
  },
  {
    minPoints: 40,
    title: "Mierenmelder",
    description: "Draagt reproduceerstappen netjes naar het team.",
    prestige: "Bronze",
    prestigeLevel: "Bronze II",
    color: "#2f6b4f",
    frameColor: "#a86f38",
    frameAccent: "#e4b36f",
    frameBackground: "#fff1df",
    rewardText: "Bronze glow",
    bugArtId: "houtmier",
    insect: "beetle",
    bugSize: 56,
    evolutionLevel: 2
  },
  {
    minPoints: 120,
    title: "Sprinkhaan Speurder",
    description: "Springt snel naar reproduceerbare bugs.",
    prestige: "Silver",
    prestigeLevel: "Silver I",
    color: "#587c2d",
    frameColor: "#9aa8ad",
    frameAccent: "#edf4f5",
    frameBackground: "#f4f8f8",
    rewardText: "Silver border",
    bugArtId: "orchidee-bidsprinkhaan",
    insect: "grasshopper",
    bugSize: 66,
    evolutionLevel: 3
  },
  {
    minPoints: 260,
    title: "Lieveheers Fixer",
    description: "Maakt van losse meldingen nette fixes.",
    prestige: "Silver",
    prestigeLevel: "Silver II",
    color: "#b83227",
    frameColor: "#84989e",
    frameAccent: "#ffffff",
    frameBackground: "#eef6f7",
    rewardText: "Silver shine",
    bugArtId: "pauwspin",
    insect: "ladybug",
    bugSize: 76,
    evolutionLevel: 4
  },
  {
    minPoints: 520,
    title: "Duizendpoot Regisseur",
    description: "Houdt meerdere flows tegelijk scherp.",
    prestige: "Gold",
    prestigeLevel: "Gold",
    color: "#8a5a2b",
    frameColor: "#d7a928",
    frameAccent: "#fff0a8",
    frameBackground: "#fff8d9",
    rewardText: "Gold frame",
    bugArtId: "smaragdlibel",
    insect: "crawler",
    bugSize: 88,
    evolutionLevel: 5
  },
  {
    minPoints: 900,
    title: "Schorpioen Sentinel",
    description: "Steekt regressies voordat ze terugkomen.",
    prestige: "Platinum",
    prestigeLevel: "Platinum",
    color: "#6f4c38",
    frameColor: "#6e9aa7",
    frameAccent: "#dff9ff",
    frameBackground: "#eefbff",
    rewardText: "Platinum aura",
    bugArtId: "schorpioen",
    insect: "crawler",
    bugSize: 96,
    evolutionLevel: 5
  },
  {
    minPoints: 1500,
    title: "Neushoorn Commander",
    description: "Duwt zware blokkades uit de release.",
    prestige: "Diamond",
    prestigeLevel: "Diamond",
    color: "#1d6f52",
    frameColor: "#4aa8ff",
    frameAccent: "#d9f4ff",
    frameBackground: "#edf8ff",
    rewardText: "Diamond frame",
    bugArtId: "olifantskever",
    insect: "beetle",
    bugSize: 104,
    evolutionLevel: 5
  },
  {
    minPoints: 2400,
    title: "Goliath BugBaas",
    description: "Legendarische eindbaas van de BugDex.",
    prestige: "Diamond",
    prestigeLevel: "Diamond Crown",
    color: "#d7bd57",
    frameColor: "#7d6bff",
    frameAccent: "#f5eeff",
    frameBackground: "#f6f1ff",
    rewardText: "Crown frame",
    bugArtId: "atlaskever",
    insect: "ladybug",
    bugSize: 112,
    evolutionLevel: 5
  },
  {
    minPoints: 5000,
    title: "Hercules Vanguard",
    description: "Draagt releases die voor anderen te zwaar worden.",
    prestige: "Master",
    prestigeLevel: "Master I",
    color: "#8f5a18",
    frameColor: "#d68121",
    frameAccent: "#fff0ba",
    frameBackground: "#fff7df",
    rewardText: "Amber master frame",
    bugArtId: "herculeskever",
    insect: "beetle",
    bugSize: 116,
    evolutionLevel: 5
  },
  {
    minPoints: 10000,
    title: "Juweel Overlord",
    description: "Vindt zeldzame fouten in elke verborgen hoek.",
    prestige: "Master",
    prestigeLevel: "Master II",
    color: "#087f78",
    frameColor: "#18b7a6",
    frameAccent: "#bffdf2",
    frameBackground: "#eafffa",
    rewardText: "Emerald master frame",
    bugArtId: "juweelkever",
    insect: "beetle",
    bugSize: 120,
    evolutionLevel: 5
  },
  {
    minPoints: 20000,
    title: "Maanvleugel Orakel",
    description: "Ziet regressies al voordat ze de nacht bereiken.",
    prestige: "Mythic",
    prestigeLevel: "Mythic",
    color: "#4968b7",
    frameColor: "#8f7cff",
    frameAccent: "#e5dcff",
    frameBackground: "#f3efff",
    rewardText: "Mythic moon frame",
    bugArtId: "maanmot",
    insect: "dragonfly",
    bugSize: 124,
    evolutionLevel: 5
  },
  {
    minPoints: 40000,
    title: "Kosmische Bugkeizer",
    description: "De bijna onbereikbare heerser van het BugBaas-universum.",
    prestige: "Cosmic",
    prestigeLevel: "Cosmic Crown",
    color: "#8e3dc4",
    frameColor: "#ff5fd7",
    frameAccent: "#fff1ff",
    frameBackground: "#fff0fb",
    rewardText: "Cosmic crown frame",
    bugArtId: "komeetmot",
    insect: "dragonfly",
    bugSize: 128,
    evolutionLevel: 5
  }
];

export const bugDexEntries: BugDexEntry[] = [
  { id: "zilvervisje", name: "Zilvervisje", title: "Stille Starter", minPoints: 0, minBugs: 0, rarity: "Gewoon", insect: "larva", evolutionLevel: 1, note: "Glipt door kleine randgevallen." },
  { id: "fruitvlieg", name: "Fruitvlieg", title: "Snelle Spotter", minPoints: 5, minBugs: 1, rarity: "Gewoon", insect: "crawler", evolutionLevel: 1, note: "Vindt bugs voordat koffie koud is." },
  { id: "bladluis", name: "Bladluis", title: "Detailknager", minPoints: 10, minBugs: 1, rarity: "Gewoon", insect: "larva", evolutionLevel: 1, note: "Knaagt aan kleine UI-foutjes." },
  { id: "mug", name: "Mug", title: "Irritatie Detector", minPoints: 20, minBugs: 2, rarity: "Gewoon", insect: "dragonfly", evolutionLevel: 1, note: "Hoort precies waar het zoemt." },
  { id: "mot", name: "Mot", title: "Nachttester", minPoints: 30, minBugs: 2, rarity: "Gewoon", insect: "crawler", evolutionLevel: 2, note: "Komt af op schermlicht en regressies." },
  { id: "mier", name: "Mier", title: "Teamdrager", minPoints: 45, minBugs: 3, rarity: "Gewoon", insect: "beetle", evolutionLevel: 2, note: "Sleept reproduceerstappen netjes mee." },
  { id: "vlo", name: "Vlo", title: "Sprongtester", minPoints: 60, minBugs: 4, rarity: "Gewoon", insect: "grasshopper", evolutionLevel: 2, note: "Springt razendsnel tussen flows." },
  { id: "pissebed", name: "Pissebed", title: "Randgevalroller", minPoints: 75, minBugs: 5, rarity: "Gewoon", insect: "crawler", evolutionLevel: 2, note: "Rolt elk hoekje van de app af." },
  { id: "stinkwants", name: "Stinkwants", title: "Codegeur Vinder", minPoints: 95, minBugs: 6, rarity: "Zeldzaam", insect: "beetle", evolutionLevel: 3, note: "Ruikt rare states op afstand." },
  { id: "snuitkever", name: "Snuitkever", title: "Diepgraver", minPoints: 115, minBugs: 7, rarity: "Zeldzaam", insect: "beetle", evolutionLevel: 3, note: "Steekt zijn neus in verborgen bugs." },
  { id: "lieveheersbeestje", name: "Lieveheersbeestje", title: "Fixvriend", minPoints: 135, minBugs: 8, rarity: "Zeldzaam", insect: "ladybug", evolutionLevel: 3, note: "Maakt bugjacht bijna schattig." },
  { id: "kakkerlak", name: "Kakkerlak", title: "Survivor Bug", minPoints: 160, minBugs: 9, rarity: "Gewoon", insect: "crawler", evolutionLevel: 3, note: "Overleeft elke hotfix." },
  { id: "oorworm", name: "Oorworm", title: "Feedbackfluisteraar", minPoints: 185, minBugs: 10, rarity: "Gewoon", insect: "larva", evolutionLevel: 3, note: "Hoort wat gebruikers niet zeggen." },
  { id: "boktor", name: "Boktor", title: "Houtgreep Tester", minPoints: 215, minBugs: 12, rarity: "Episch", insect: "beetle", evolutionLevel: 4, note: "Bijt door taaie legacy schermen." },
  { id: "tapijtkever", name: "Tapijtkever", title: "Pixelpluizer", minPoints: 245, minBugs: 13, rarity: "Zeldzaam", insect: "ladybug", evolutionLevel: 4, note: "Ziet elke scheve spacing." },
  { id: "roofwants", name: "Roofwants", title: "Bugjager", minPoints: 275, minBugs: 14, rarity: "Zeldzaam", insect: "beetle", evolutionLevel: 4, note: "Jaagt actief op de lastigste cases." },
  { id: "duizendpoot", name: "Duizendpoot", title: "Multitask Master", minPoints: 310, minBugs: 16, rarity: "Zeldzaam", insect: "crawler", evolutionLevel: 4, note: "Test alles tegelijk, bijna." },
  { id: "sprinkhaan", name: "Sprinkhaan", title: "Flow Springer", minPoints: 350, minBugs: 18, rarity: "Zeldzaam", insect: "grasshopper", evolutionLevel: 4, note: "Springt door onboarding, lijst en detail." },
  { id: "wesp", name: "Wesp", title: "Scherpe Prikker", minPoints: 395, minBugs: 20, rarity: "Zeldzaam", insect: "dragonfly", evolutionLevel: 4, note: "Prikt precies in pijnpunten." },
  { id: "hoornaar", name: "Hoornaar", title: "Escalatiebaas", minPoints: 445, minBugs: 22, rarity: "Episch", insect: "dragonfly", evolutionLevel: 5, note: "Laat kritieke bugs niet ontsnappen." },
  { id: "schorpioen", name: "Schorpioen", title: "Regressiesteker", minPoints: 500, minBugs: 24, rarity: "Legendarisch", insect: "crawler", evolutionLevel: 5, note: "Steekt terug bij terugkerende bugs." },
  { id: "termiet", name: "Termiet", title: "Structuurvreter", minPoints: 560, minBugs: 26, rarity: "Gewoon", insect: "beetle", evolutionLevel: 5, note: "Vindt wat onder de vloer zit." },
  { id: "mestkever", name: "Mestkever", title: "Cleanup Kampioen", minPoints: 625, minBugs: 28, rarity: "Zeldzaam", insect: "beetle", evolutionLevel: 5, note: "Ruimt oude rommelbugs op." },
  { id: "wandelende-tak", name: "Wandelende tak", title: "Camouflage Case", minPoints: 695, minBugs: 30, rarity: "Zeldzaam", insect: "grasshopper", evolutionLevel: 5, note: "Vindt bugs die zich verstoppen." },
  { id: "vogelspin", name: "Vogelspin", title: "Sprintbaas", minPoints: 770, minBugs: 33, rarity: "Episch", insect: "crawler", evolutionLevel: 5, note: "Groot, duidelijk, niet te negeren." },
  { id: "reuzenkakkerlak", name: "Reuzenkakkerlak", title: "Incident Survivor", minPoints: 850, minBugs: 36, rarity: "Episch", insect: "ladybug", evolutionLevel: 5, note: "Heeft productiepaniek gezien." },
  { id: "reuzen-duizendpoot", name: "Reuzenduizendpoot", title: "Flow Monster", minPoints: 935, minBugs: 39, rarity: "Legendarisch", insect: "crawler", evolutionLevel: 5, note: "Heeft voor elke tab een poot." },
  { id: "neushoornkever", name: "Neushoornkever", title: "Heavy Hitter", minPoints: 1025, minBugs: 42, rarity: "Legendarisch", insect: "beetle", evolutionLevel: 5, note: "Duwt blokkades uit de weg." },
  { id: "atlaskever", name: "Atlaskever", title: "Werelddrager", minPoints: 1120, minBugs: 45, rarity: "Legendarisch", insect: "beetle", evolutionLevel: 5, note: "Draagt de hele backlog." },
  { id: "herculeskever", name: "Herculeskever", title: "Krachtpatser", minPoints: 1225, minBugs: 48, rarity: "Legendarisch", insect: "beetle", evolutionLevel: 5, note: "Tilt zelfs kritieke releases." },
  { id: "goliathkever", name: "Goliathkever", title: "BugDex Legende", minPoints: 1350, minBugs: 50, rarity: "Legendarisch", insect: "ladybug", evolutionLevel: 5, note: "Alleen de fanatiekste jagers komen hier." },
  { id: "motmug", name: "Motmug", title: "Fuzzy Finder", minPoints: 8, minBugs: 1, rarity: "Gewoon", insect: "dragonfly", evolutionLevel: 1, note: "Klein, pluizig en opvallend aanwezig." },
  { id: "langpootmug", name: "Langpootmug", title: "Fragiele Klikker", minPoints: 12, minBugs: 1, rarity: "Gewoon", insect: "dragonfly", evolutionLevel: 1, note: "Veel poot, weinig paniek." },
  { id: "faraomier", name: "Faraomier", title: "Mini Manager", minPoints: 18, minBugs: 1, rarity: "Gewoon", insect: "beetle", evolutionLevel: 1, note: "Klein account, groot plan." },
  { id: "boekluis", name: "Boekluis", title: "Documentduiker", minPoints: 22, minBugs: 1, rarity: "Gewoon", insect: "larva", evolutionLevel: 1, note: "Vindt typo's in de kleine lettertjes." },
  { id: "stofluis", name: "Stofluis", title: "Stille Scanner", minPoints: 28, minBugs: 2, rarity: "Gewoon", insect: "larva", evolutionLevel: 1, note: "Ziet wat onder de UI-stoflaag zit." },
  { id: "teek", name: "Teek", title: "Kleine Risicofactor", minPoints: 38, minBugs: 2, rarity: "Gewoon", insect: "crawler", evolutionLevel: 2, note: "Niet groot, wel irritant effectief." },
  { id: "fluweelmijt", name: "Fluweelmijt", title: "Rode Flitser", minPoints: 52, minBugs: 3, rarity: "Gewoon", insect: "crawler", evolutionLevel: 2, note: "Zacht uiterlijk, scherpe timing." },
  { id: "schildwants", name: "Schildwants", title: "Badge Schild", minPoints: 88, minBugs: 5, rarity: "Zeldzaam", insect: "beetle", evolutionLevel: 3, note: "Draagt zijn eigen UI-frame mee." },
  { id: "houtmier", name: "Houtmier", title: "Kolonie Kapitein", minPoints: 105, minBugs: 6, rarity: "Zeldzaam", insect: "beetle", evolutionLevel: 3, note: "Teamwork met rood-zwarte focus." },
  { id: "kniptor", name: "Kniptor", title: "Click Tester", minPoints: 125, minBugs: 7, rarity: "Zeldzaam", insect: "beetle", evolutionLevel: 3, note: "Springt precies wanneer je niet kijkt." },
  { id: "loopkever", name: "Loopkever", title: "Race Runner", minPoints: 145, minBugs: 8, rarity: "Zeldzaam", insect: "grasshopper", evolutionLevel: 3, note: "Rent door regressies heen." },
  { id: "waterkever", name: "Waterkever", title: "Gladde Zwemmer", minPoints: 175, minBugs: 9, rarity: "Zeldzaam", insect: "beetle", evolutionLevel: 3, note: "Laat geen ripple ongetest." },
  { id: "schrijvertje", name: "Schrijvertje", title: "Ripple Reviewer", minPoints: 205, minBugs: 10, rarity: "Gewoon", insect: "dragonfly", evolutionLevel: 2, note: "Draait rondjes om twijfelachtige states." },
  { id: "schaatsenrijder", name: "Schaatsenrijder", title: "Surface Skater", minPoints: 235, minBugs: 11, rarity: "Zeldzaam", insect: "grasshopper", evolutionLevel: 2, note: "Blijft bovenop elk issue." },
  { id: "goudtor", name: "Goudtor", title: "Luxe Logger", minPoints: 285, minBugs: 14, rarity: "Zeldzaam", insect: "beetle", evolutionLevel: 4, note: "Glimt alsof de bug al gefixt is." },
  { id: "tijgerkever", name: "Tijgerkever", title: "Sprint Hunter", minPoints: 325, minBugs: 16, rarity: "Zeldzaam", insect: "grasshopper", evolutionLevel: 4, note: "Snelle kaken, snelle feedback." },
  { id: "doodgraver", name: "Doodgraver", title: "Incident Delver", minPoints: 370, minBugs: 18, rarity: "Zeldzaam", insect: "crawler", evolutionLevel: 4, note: "Begraaft terugkerende bugs voorgoed." },
  { id: "waterschorpioen", name: "Waterschorpioen", title: "Ademstaart Analyst", minPoints: 420, minBugs: 20, rarity: "Zeldzaam", insect: "crawler", evolutionLevel: 4, note: "Vreemd silhouet, nuttige vondst." },
  { id: "bidsprinkhaan", name: "Bidsprinkhaan", title: "Ninja Fixer", minPoints: 470, minBugs: 22, rarity: "Episch", insect: "grasshopper", evolutionLevel: 5, note: "Wacht stil, grijpt precies raak." },
  { id: "wandelend-blad", name: "Wandelend blad", title: "Stealth Leaf", minPoints: 530, minBugs: 25, rarity: "Episch", insect: "grasshopper", evolutionLevel: 5, note: "Ziet eruit als decor, test als pro." },
  { id: "wespspin", name: "Wespspin", title: "Web Badge", minPoints: 590, minBugs: 27, rarity: "Zeldzaam", insect: "crawler", evolutionLevel: 4, note: "Webt bugs vast voordat ze ontsnappen." },
  { id: "kruisspin", name: "Kruisspin", title: "Pattern Watcher", minPoints: 655, minBugs: 29, rarity: "Zeldzaam", insect: "crawler", evolutionLevel: 4, note: "Heeft altijd een draadje naar oorzaak." },
  { id: "springspin", name: "Springspin", title: "Scout Ogen", minPoints: 725, minBugs: 31, rarity: "Zeldzaam", insect: "crawler", evolutionLevel: 4, note: "Compacte scout met grote ogen." },
  { id: "libel", name: "Libel", title: "Crystal Wing", minPoints: 800, minBugs: 34, rarity: "Episch", insect: "dragonfly", evolutionLevel: 5, note: "Glazen vleugels, messcherpe flow." },
  { id: "waterjuffer", name: "Waterjuffer", title: "Elegant Trace", minPoints: 875, minBugs: 37, rarity: "Episch", insect: "dragonfly", evolutionLevel: 4, note: "Dun, snel en verrassend precies." },
  { id: "gaasvlieg", name: "Gaasvlieg", title: "Netwerk Ninja", minPoints: 955, minBugs: 40, rarity: "Episch", insect: "dragonfly", evolutionLevel: 4, note: "Doorzichtige vleugels, heldere analyse." },
  { id: "doodshoofdvlinder", name: "Doodshoofdvlinder", title: "Mysterie Melder", minPoints: 1040, minBugs: 43, rarity: "Episch", insect: "dragonfly", evolutionLevel: 5, note: "Komt tevoorschijn bij donkere edge cases." },
  { id: "kolibrievlinder", name: "Kolibrievlinder", title: "Hover Hunter", minPoints: 1130, minBugs: 46, rarity: "Episch", insect: "dragonfly", evolutionLevel: 5, note: "Blijft hangen tot het probleem duidelijk is." },
  { id: "koninginnenpage", name: "Koninginnenpage", title: "Premium Page", minPoints: 1230, minBugs: 49, rarity: "Episch", insect: "dragonfly", evolutionLevel: 5, note: "Sierlijk, zeldzaam en releasewaardig." },
  { id: "atalanta", name: "Atalanta", title: "Contrast Catcher", minPoints: 1335, minBugs: 52, rarity: "Episch", insect: "dragonfly", evolutionLevel: 5, note: "Zwart-oranje alarm voor visuele bugs." },
  { id: "dagpauwoog", name: "Dagpauwoog", title: "Watcher Wing", minPoints: 1445, minBugs: 55, rarity: "Episch", insect: "dragonfly", evolutionLevel: 5, note: "Ziet alles, ook wat jij mist." },
  { id: "eikenprocessierups", name: "Eikenprocessierups", title: "Colonne Checker", minPoints: 1560, minBugs: 58, rarity: "Zeldzaam", insect: "larva", evolutionLevel: 4, note: "Loopt niet alleen; bugs meestal ook niet." },
  { id: "pijlstaartrups", name: "Pijlstaartrups", title: "Tail Signal", minPoints: 1680, minBugs: 61, rarity: "Episch", insect: "larva", evolutionLevel: 4, note: "Heeft een staartpunt voor urgente hints." },
  { id: "cicade", name: "Cicade", title: "Signal Singer", minPoints: 1805, minBugs: 64, rarity: "Zeldzaam", insect: "dragonfly", evolutionLevel: 5, note: "Laat regressies niet stil blijven." },
  { id: "schuimcicade", name: "Schuimcicade", title: "Bubble Scout", minPoints: 1935, minBugs: 67, rarity: "Gewoon", insect: "dragonfly", evolutionLevel: 4, note: "Speels schuim, serieuze vondst." },
  { id: "vliegend-hert", name: "Vliegend hert", title: "Gewei Generaal", minPoints: 2070, minBugs: 70, rarity: "Legendarisch", insect: "beetle", evolutionLevel: 5, note: "Grote kaken voor grote blockers." },
  { id: "juweelkever", name: "Juweelkever", title: "Shimmer Elite", minPoints: 2210, minBugs: 75, rarity: "Episch", insect: "beetle", evolutionLevel: 5, note: "Metallic glans, premium badge-energie." },
  { id: "orchidee-bidsprinkhaan", name: "Orchidee-bidsprinkhaan", title: "Bloom Ambusher", minPoints: 2260, minBugs: 76, rarity: "Legendarisch", insect: "grasshopper", evolutionLevel: 5, note: "Elegant bloemblad, gevaarlijk goede timing." },
  { id: "pauwspin", name: "Pauwspin", title: "Show-off Scout", minPoints: 2310, minBugs: 77, rarity: "Episch", insect: "crawler", evolutionLevel: 5, note: "Klein, kleurrijk en veel te zelfverzekerd." },
  { id: "juweelwesp", name: "Juweelwesp", title: "Metallic Prikker", minPoints: 2360, minBugs: 78, rarity: "Episch", insect: "dragonfly", evolutionLevel: 5, note: "Luxueus glimmend, maar nog steeds scherp." },
  { id: "goudschildkever", name: "Goudschildkever", title: "Medaille Schild", minPoints: 2410, minBugs: 79, rarity: "Episch", insect: "beetle", evolutionLevel: 5, note: "Rond, goud en klaar voor het podium." },
  { id: "harlekijnwants", name: "Harlekijnwants", title: "Warning Pattern", minPoints: 2460, minBugs: 80, rarity: "Episch", insect: "beetle", evolutionLevel: 4, note: "Ziet eruit als een waarschuwing, gedraagt zich ook zo." },
  { id: "lantaarnvlieg", name: "Lantaarnvlieg", title: "Mystery Marker", minPoints: 2510, minBugs: 81, rarity: "Episch", insect: "dragonfly", evolutionLevel: 4, note: "Rare kop, rare bug, prima match." },
  { id: "vioolspin", name: "Vioolspin", title: "Stille Risico", minPoints: 2560, minBugs: 82, rarity: "Episch", insect: "crawler", evolutionLevel: 3, note: "Niet groot, wel reden om op te letten." },
  { id: "gespikkelde-houtvlinder", name: "Gespikkelde houtvlinder", title: "Silent Timber", minPoints: 2610, minBugs: 83, rarity: "Episch", insect: "dragonfly", evolutionLevel: 4, note: "Camouflage voor stille regressies." },
  { id: "zebra-springspin", name: "Zebra-springspin", title: "Stripe Scout", minPoints: 2660, minBugs: 84, rarity: "Episch", insect: "crawler", evolutionLevel: 4, note: "Grote ogen, korte sprong, scherpe vondst." },
  { id: "smaragdlibel", name: "Smaragdlibel", title: "Clean Flight", minPoints: 2710, minBugs: 85, rarity: "Legendarisch", insect: "dragonfly", evolutionLevel: 5, note: "Groen metallic en strak door elke flow." },
  { id: "glasvleugelvlinder", name: "Glasvleugelvlinder", title: "Holo Wing", minPoints: 2760, minBugs: 86, rarity: "Episch", insect: "dragonfly", evolutionLevel: 5, note: "Bijna onzichtbaar, behalve voor goede testers." },
  { id: "komeetmot", name: "Komeetmot", title: "Tail Flair", minPoints: 2810, minBugs: 87, rarity: "Episch", insect: "dragonfly", evolutionLevel: 5, note: "Laat een spoor van nette tickets achter." },
  { id: "maanmot", name: "Maanmot", title: "Soft Glow", minPoints: 2860, minBugs: 88, rarity: "Episch", insect: "dragonfly", evolutionLevel: 5, note: "Rustige glow, serieuze vondst." },
  { id: "atlasvlinder", name: "Atlasvlinder", title: "Wing Boss", minPoints: 2910, minBugs: 89, rarity: "Legendarisch", insect: "dragonfly", evolutionLevel: 5, note: "Enorme vleugels voor enorme edge cases." },
  { id: "rozekever", name: "Rozekever", title: "Rose Shield", minPoints: 2960, minBugs: 90, rarity: "Zeldzaam", insect: "beetle", evolutionLevel: 4, note: "Compact premium schild met kleur." },
  { id: "kardinaalkever", name: "Kardinaalkever", title: "Urgent Runner", minPoints: 3010, minBugs: 91, rarity: "Episch", insect: "beetle", evolutionLevel: 4, note: "Rood genoeg om prioriteit te krijgen." },
  { id: "vuurwants", name: "Vuurwants", title: "Signal Bug", minPoints: 3060, minBugs: 92, rarity: "Zeldzaam", insect: "beetle", evolutionLevel: 3, note: "Strak rood-zwart, geen twijfel mogelijk." },
  { id: "sabelsprinkhaan", name: "Sabelsprinkhaan", title: "Sharp Stepper", minPoints: 3110, minBugs: 93, rarity: "Episch", insect: "grasshopper", evolutionLevel: 4, note: "Lange sprieten, scherp detail." },
  { id: "mierenleeuw", name: "Mierenleeuw", title: "Trap Hunter", minPoints: 3160, minBugs: 94, rarity: "Gewoon", insect: "larva", evolutionLevel: 4, note: "Graafkuil voor verborgen bugs." },
  { id: "dobsonvlieg", name: "Dobsonvlieg", title: "Jaw Dropper", minPoints: 3210, minBugs: 95, rarity: "Legendarisch", insect: "dragonfly", evolutionLevel: 5, note: "Kaken waar blockers stil van worden." },
  { id: "helikopterjuffer", name: "Helikopterjuffer", title: "Air Trace", minPoints: 3260, minBugs: 96, rarity: "Episch", insect: "dragonfly", evolutionLevel: 4, note: "Technisch, luchtig en snel." },
  { id: "spookinsect", name: "Spookinsect", title: "Ghost Case", minPoints: 3310, minBugs: 97, rarity: "Legendarisch", insect: "grasshopper", evolutionLevel: 5, note: "Stealth bug die ineens overal is." },
  { id: "bladpootwants", name: "Bladpootwants", title: "Odd Silhouette", minPoints: 3360, minBugs: 98, rarity: "Episch", insect: "beetle", evolutionLevel: 4, note: "Vreemde poten, handig profiel." },
  { id: "assassin-bug", name: "Assassin bug", title: "Precision Hunter", minPoints: 3410, minBugs: 99, rarity: "Legendarisch", insect: "beetle", evolutionLevel: 5, note: "Jaagt op bugs zonder veel lawaai." },
  { id: "tijgermug", name: "Tijgermug", title: "Mini Danger", minPoints: 3460, minBugs: 100, rarity: "Episch", insect: "dragonfly", evolutionLevel: 4, note: "Klein, gestreept, berucht effectief." },
  { id: "dolksteekwesp", name: "Dolksteekwesp", title: "Critical Sting", minPoints: 3510, minBugs: 101, rarity: "Legendarisch", insect: "dragonfly", evolutionLevel: 5, note: "Voor bugs met echte urgentie." },
  { id: "roofvlieg", name: "Roofvlieg", title: "Aerial Hunter", minPoints: 3560, minBugs: 102, rarity: "Episch", insect: "dragonfly", evolutionLevel: 4, note: "Harige speurder met jagerhouding." },
  { id: "kameelhalsvlieg", name: "Kameelhalsvlieg", title: "Long Neck Lookout", minPoints: 3610, minBugs: 103, rarity: "Episch", insect: "dragonfly", evolutionLevel: 4, note: "Bizar profiel, prima herkenbaar." },
  { id: "zweefvlieg", name: "Zweefvlieg", title: "Friendly Hover", minPoints: 3660, minBugs: 104, rarity: "Gewoon", insect: "dragonfly", evolutionLevel: 3, note: "Ziet er dreigend uit, test vriendelijk." },
  { id: "goudwesp", name: "Goudwesp", title: "Golden Sting", minPoints: 3710, minBugs: 105, rarity: "Episch", insect: "dragonfly", evolutionLevel: 5, note: "Juweelachtig en belonend." },
  { id: "sluipwesp", name: "Sluipwesp", title: "Mystery Stinger", minPoints: 3735, minBugs: 105, rarity: "Zeldzaam", insect: "dragonfly", evolutionLevel: 4, note: "Smal, scherp en net iets te stil." },
  { id: "fluweelmier", name: "Fluweelmier", title: "Soft Sting", minPoints: 3760, minBugs: 106, rarity: "Episch", insect: "beetle", evolutionLevel: 4, note: "Zacht uiterlijk, pittige feedback." },
  { id: "reuzenwaterwants", name: "Reuzenwaterwants", title: "Water Tank", minPoints: 3810, minBugs: 107, rarity: "Legendarisch", insect: "crawler", evolutionLevel: 5, note: "Plat, breed en onmogelijk te missen." },
  { id: "zweepschorpioen", name: "Zweepschorpioen", title: "Whip Tail", minPoints: 3860, minBugs: 108, rarity: "Legendarisch", insect: "crawler", evolutionLevel: 5, note: "Dreigend silhouet voor harde regressies." },
  { id: "azuren-waterjuffer", name: "Azuren waterjuffer", title: "Azure Trace", minPoints: 3910, minBugs: 109, rarity: "Episch", insect: "dragonfly", evolutionLevel: 4, note: "Blauw, snel en fris." },
  { id: "rouwmantelvlinder", name: "Rouwmantelvlinder", title: "Serious Wing", minPoints: 3960, minBugs: 110, rarity: "Legendarisch", insect: "dragonfly", evolutionLevel: 5, note: "Chique donker met scherpe rand." },
  { id: "keizersmantel", name: "Keizersmantel", title: "Royal Orange", minPoints: 4010, minBugs: 111, rarity: "Legendarisch", insect: "dragonfly", evolutionLevel: 5, note: "Koninklijke badge voor nette meldingen." },
  { id: "gouden-tor", name: "Gouden tor", title: "Clean Gold", minPoints: 4060, minBugs: 112, rarity: "Zeldzaam", insect: "beetle", evolutionLevel: 4, note: "Glanzend rank-icoon zonder poespas." },
  { id: "soldaatje", name: "Soldaatje", title: "Field Unit", minPoints: 4110, minBugs: 113, rarity: "Zeldzaam", insect: "beetle", evolutionLevel: 3, note: "Kleine veldwerker met duidelijke kleur." },
  { id: "doodgraverkever", name: "Doodgraverkever", title: "Heavy Cleanup", minPoints: 4160, minBugs: 114, rarity: "Episch", insect: "crawler", evolutionLevel: 4, note: "Ruig genoeg voor zware bugmeldingen." },
  { id: "olifantskever", name: "Olifantskever", title: "Massive Push", minPoints: 4210, minBugs: 115, rarity: "Legendarisch", insect: "beetle", evolutionLevel: 5, note: "Massief, sterk en niet subtiel." },
  { id: "regenboogmestkever", name: "Regenboogmestkever", title: "Rainbow Cleanup", minPoints: 4260, minBugs: 116, rarity: "Legendarisch", insect: "beetle", evolutionLevel: 5, note: "Grappig idee, premium uitvoering." },
  { id: "titanus-kever", name: "Titanus-kever", title: "Titan Jaw", minPoints: 4310, minBugs: 117, rarity: "Legendarisch", insect: "beetle", evolutionLevel: 5, note: "Eindbaas-boktor voor eindbaas-bugs." },
  { id: "langsprietboktor", name: "Langsprietboktor", title: "Signal Antenna", minPoints: 4360, minBugs: 118, rarity: "Episch", insect: "beetle", evolutionLevel: 4, note: "Antennebereik tot in legacy code." },
  { id: "schildpadkever", name: "Schildpadkever", title: "Defense Frame", minPoints: 4410, minBugs: 119, rarity: "Episch", insect: "beetle", evolutionLevel: 4, note: "Transparant randje, stevige verdediging." },
  { id: "vuurkever", name: "Vuurkever", title: "Red Alert", minPoints: 4460, minBugs: 120, rarity: "Zeldzaam", insect: "beetle", evolutionLevel: 4, note: "Strakke waarschuwingskleur." },
  { id: "blauwe-ertsbij", name: "Blauwe ertsbij", title: "Blue Premium", minPoints: 4510, minBugs: 121, rarity: "Legendarisch", insect: "dragonfly", evolutionLevel: 5, note: "Koel blauw, zeldzame beloning." },
  { id: "wespboktor", name: "Wespboktor", title: "Danger Disguise", minPoints: 4560, minBugs: 122, rarity: "Episch", insect: "beetle", evolutionLevel: 4, note: "Camouflage en gevaar in een." },
  { id: "groene-zandloopkever", name: "Groene zandloopkever", title: "Speed Precision", minPoints: 4610, minBugs: 123, rarity: "Legendarisch", insect: "grasshopper", evolutionLevel: 5, note: "Metallic groene jager met tempo." },
  { id: "lauwstaartwaterjuffer", name: "Lauwstaartwaterjuffer", title: "Blue Tail Trace", minPoints: 4660, minBugs: 124, rarity: "Episch", insect: "dragonfly", evolutionLevel: 4, note: "Slanke vleugels, blauwe staart en scherpe trace." },
  { id: "roodwitte-celspin", name: "Roodwitte celspin", title: "Cellar Signal", minPoints: 4710, minBugs: 125, rarity: "Episch", insect: "crawler", evolutionLevel: 4, note: "Donkere glans met rood-witte alarmsignalen." },
  { id: "koningin-alexandravlinder", name: "Koningin-Alexandravlinder", title: "Royal Wing", minPoints: 4800, minBugs: 126, rarity: "Mythisch", insect: "dragonfly", evolutionLevel: 5, note: "Zeldzaam, enorm en bijna koninklijk in de lucht." },
  { id: "zonsondergangsmot", name: "Zonsondergangsmot", title: "Prism Wing", minPoints: 4880, minBugs: 127, rarity: "Mythisch", insect: "dragonfly", evolutionLevel: 5, note: "Kleuren alsof de release door een prisma gaat." },
  { id: "picasso-wants", name: "Picasso-wants", title: "Pattern Master", minPoints: 4960, minBugs: 128, rarity: "Mythisch", insect: "beetle", evolutionLevel: 5, note: "Een levend kunstwerk met waarschuwingspatroon." },
  { id: "roze-esdoornmot", name: "Roze esdoornmot", title: "Candy Glow", minPoints: 5040, minBugs: 129, rarity: "Mythisch", insect: "dragonfly", evolutionLevel: 5, note: "Zacht roze-geel, maar opvallend genoeg voor de top tier." },
  { id: "giraffekevertje", name: "Giraffekevertje", title: "Long Neck Scout", minPoints: 5120, minBugs: 130, rarity: "Mythisch", insect: "beetle", evolutionLevel: 5, note: "Een bizarre lange nek voor bugs die ver vooruit kijken." },
  { id: "doornbloembidsprinkhaan", name: "Doornbloembidsprinkhaan", title: "Bloom Blade", minPoints: 5200, minBugs: 131, rarity: "Mythisch", insect: "grasshopper", evolutionLevel: 5, note: "Bloemachtig, stekelig en klaar om precies toe te slaan." },
  { id: "lantaarndrager", name: "Lantaarndrager", title: "Signal Lantern", minPoints: 5280, minBugs: 132, rarity: "Mythisch", insect: "dragonfly", evolutionLevel: 5, note: "Vreemde snuit, felle vleugels en direct herkenbaar." },
  { id: "glorieuze-scarabee", name: "Glorieuze scarabee", title: "Mirror Shield", minPoints: 5360, minBugs: 133, rarity: "Mythisch", insect: "beetle", evolutionLevel: 5, note: "Een spiegelende scarabee met echte eindtier-uitstraling." },
  { id: "bromvlieg", name: "Bromvlieg", title: "Noise Finder", minPoints: 5380, minBugs: 132, rarity: "Gewoon", insect: "dragonfly", evolutionLevel: 3, note: "Maakt veel geluid zodra iets niet lekker loopt." },
  { id: "dwergcicade", name: "Dwergcicade", title: "Mini Signal", minPoints: 5390, minBugs: 133, rarity: "Gewoon", insect: "dragonfly", evolutionLevel: 3, note: "Klein signaal, scherp gevonden." },
  { id: "groene-junikever", name: "Groene junikever", title: "Emerald Runner", minPoints: 5400, minBugs: 134, rarity: "Zeldzaam", insect: "beetle", evolutionLevel: 4, note: "Metallic groen pantser geeft deze junikever een zeldzame glans." },
  { id: "hommel", name: "Hommel", title: "Fuzzy Worker", minPoints: 5410, minBugs: 135, rarity: "Gewoon", insect: "dragonfly", evolutionLevel: 3, note: "Pluizige werker voor simpele vondsten." },
  { id: "huisvlieg", name: "Huisvlieg", title: "Kitchen Scout", minPoints: 5420, minBugs: 136, rarity: "Gewoon", insect: "dragonfly", evolutionLevel: 3, note: "Duikt overal op waar iets blijft liggen." },
  { id: "kleermot", name: "Kleermot", title: "Fabric Nibbler", minPoints: 5430, minBugs: 137, rarity: "Gewoon", insect: "dragonfly", evolutionLevel: 3, note: "Knaagt stil aan kleine details." },
  { id: "meikever", name: "Meikever", title: "Spring Beetle", minPoints: 5440, minBugs: 138, rarity: "Gewoon", insect: "beetle", evolutionLevel: 3, note: "Klassieke kever met stevige aanwezigheid." },
  { id: "schorpioenvlieg", name: "Schorpioenvlieg", title: "Tail Signal", minPoints: 5450, minBugs: 139, rarity: "Episch", insect: "dragonfly", evolutionLevel: 4, note: "De opvallend gekromde staart maakt dit silhouet direct episch." },
  { id: "voorraadmot", name: "Voorraadmot", title: "Pantry Ping", minPoints: 5460, minBugs: 140, rarity: "Gewoon", insect: "dragonfly", evolutionLevel: 3, note: "Zit verstopt tussen oude randgevallen." },
  { id: "whitefly", name: "Whitefly", title: "Leaf Drifter", minPoints: 5470, minBugs: 141, rarity: "Gewoon", insect: "dragonfly", evolutionLevel: 3, note: "Klein wit signaal boven de bladeren." },
  { id: "witte-tijger", name: "Witte tijger", title: "Stripe Scout", minPoints: 5480, minBugs: 142, rarity: "Zeldzaam", insect: "dragonfly", evolutionLevel: 4, note: "Het witte tijgerpatroon geeft deze nachtvlinder een zeldzame uitstraling." },
  { id: "zadelrups", name: "Zadelrups", title: "Saddle Guard", minPoints: 5490, minBugs: 143, rarity: "Episch", insect: "larva", evolutionLevel: 4, note: "Felgroen zadel met een stekelige rand." },
  { id: "reuzenpantervlinder", name: "Reuzenpantervlinder", title: "Spotlight Wing", minPoints: 5500, minBugs: 144, rarity: "Episch", insect: "dragonfly", evolutionLevel: 4, note: "Witte vleugels met krachtige zwarte vlekken." },
  { id: "monarchvlinder", name: "Monarchvlinder", title: "Migration Wing", minPoints: 5510, minBugs: 145, rarity: "Episch", insect: "dragonfly", evolutionLevel: 4, note: "Oranje trekvlinder met een iconisch patroon." },
  { id: "zakdrager", name: "Zakdrager", title: "Portable Hideout", minPoints: 5520, minBugs: 146, rarity: "Zeldzaam", insect: "larva", evolutionLevel: 4, note: "Draagt zijn camouflagehuis altijd mee." },
  { id: "gehakkelde-aurelia", name: "Gehakkelde aurelia", title: "Jagged Wing", minPoints: 5530, minBugs: 147, rarity: "Zeldzaam", insect: "dragonfly", evolutionLevel: 4, note: "Kartelvleugels met warm oranje contrast." },
  { id: "blauwe-morpho", name: "Blauwe morpho", title: "Azure Crown", minPoints: 5540, minBugs: 148, rarity: "Mythisch", insect: "dragonfly", evolutionLevel: 5, note: "Intens blauw met echte eindtier-uitstraling." },
  { id: "spinnendoder", name: "Spinnendoder", title: "Hunter Wasp", minPoints: 5550, minBugs: 149, rarity: "Episch", insect: "dragonfly", evolutionLevel: 4, note: "Lange poten en oranje jachtvleugels." },
  { id: "kameelspin", name: "Kameelspin", title: "Desert Jaws", minPoints: 5560, minBugs: 150, rarity: "Episch", insect: "crawler", evolutionLevel: 4, note: "Snelle woestijnjager met opvallende kaken." },
  { id: "hooiwagen", name: "Hooiwagen", title: "Long Step", minPoints: 5570, minBugs: 151, rarity: "Gewoon", insect: "crawler", evolutionLevel: 3, note: "Klein lijf op uitzonderlijk lange poten." },
  { id: "zweepspin", name: "Zweepspin", title: "Whip Shadow", minPoints: 5580, minBugs: 152, rarity: "Legendarisch", insect: "crawler", evolutionLevel: 5, note: "Vreemde grijparmen geven een legendarisch silhouet." },
  { id: "doorncicade", name: "Doorncicade", title: "Thorn Shield", minPoints: 5590, minBugs: 153, rarity: "Episch", insect: "beetle", evolutionLevel: 4, note: "Lijkt meer op een stekel dan op een insect." },
  { id: "kortschildkever", name: "Kortschildkever", title: "Short Armor", minPoints: 5600, minBugs: 154, rarity: "Zeldzaam", insect: "beetle", evolutionLevel: 4, note: "Compact pantser laat het achterlijf zichtbaar." },
  { id: "uilvlinder", name: "Uilvlinder", title: "Owl Eyes", minPoints: 5610, minBugs: 155, rarity: "Episch", insect: "dragonfly", evolutionLevel: 4, note: "Grote oogvlekken houden belagers op afstand." },
  { id: "groot-avondrood", name: "Groot avondrood", title: "Rose Rocket", minPoints: 5620, minBugs: 156, rarity: "Episch", insect: "dragonfly", evolutionLevel: 4, note: "Roze pijlstaart met een gestroomlijnd profiel." },
  { id: "alpenboktor", name: "Alpenboktor", title: "Alpine Blue", minPoints: 5630, minBugs: 157, rarity: "Legendarisch", insect: "beetle", evolutionLevel: 5, note: "Hemelsblauw pantser en extreem lange sprieten." },
  { id: "veenmol", name: "Veenmol", title: "Tunnel Claw", minPoints: 5640, minBugs: 158, rarity: "Episch", insect: "grasshopper", evolutionLevel: 4, note: "Graafpoten gebouwd voor ondergrondse missies." },
  { id: "schietmot", name: "Schietmot", title: "Stream Drifter", minPoints: 5650, minBugs: 159, rarity: "Gewoon", insect: "dragonfly", evolutionLevel: 3, note: "Rustige watervleugel met lange voelsprieten." },
  { id: "eendagsvlieg", name: "Eendagsvlieg", title: "One Day Wing", minPoints: 5660, minBugs: 160, rarity: "Zeldzaam", insect: "dragonfly", evolutionLevel: 4, note: "Een korte vlucht met een sierlijke staart." },
  { id: "oranjetipje", name: "Oranjetipje", title: "Orange Signal", minPoints: 5670, minBugs: 161, rarity: "Zeldzaam", insect: "dragonfly", evolutionLevel: 4, note: "Witte vleugels met scherpe oranje punten." },
  { id: "kleine-vuurvlinder", name: "Kleine vuurvlinder", title: "Copper Spark", minPoints: 5680, minBugs: 162, rarity: "Zeldzaam", insect: "dragonfly", evolutionLevel: 4, note: "Kleine vleugels met koperkleurige gloed." },
  { id: "dikkopje", name: "Dikkopje", title: "Meadow Dash", minPoints: 5690, minBugs: 163, rarity: "Gewoon", insect: "dragonfly", evolutionLevel: 3, note: "Compacte graslandvlinder met snelle vlucht." },
  { id: "veldkrekel", name: "Veldkrekel", title: "Field Chirp", minPoints: 5700, minBugs: 164, rarity: "Gewoon", insect: "grasshopper", evolutionLevel: 3, note: "Klassieke zanger van warme grasvelden." },
  { id: "coloradokever", name: "Coloradokever", title: "Stripe Armor", minPoints: 5710, minBugs: 165, rarity: "Zeldzaam", insect: "beetle", evolutionLevel: 4, note: "Rond pantser met opvallende lengtestrepen." },
  { id: "meeltor", name: "Meeltor", title: "Pantry Armor", minPoints: 5720, minBugs: 166, rarity: "Gewoon", insect: "beetle", evolutionLevel: 3, note: "Donkere voorraadkever met stevig pantser." },
  { id: "roodbruine-rijstmeelkever", name: "Roodbruine rijstmeelkever", title: "Grain Scout", minPoints: 5730, minBugs: 167, rarity: "Gewoon", insect: "beetle", evolutionLevel: 3, note: "Kleine roodbruine speurder tussen het graan." },
  { id: "schorskever", name: "Schorskever", title: "Bark Borer", minPoints: 5740, minBugs: 168, rarity: "Gewoon", insect: "beetle", evolutionLevel: 3, note: "Boort verborgen routes onder boomschors." },
  { id: "glimworm", name: "Glimworm", title: "Night Beacon", minPoints: 5750, minBugs: 169, rarity: "Zeldzaam", insect: "beetle", evolutionLevel: 4, note: "Een levend groen lampje voor donkere nachten." },
  { id: "zijdevlinder", name: "Zijdevlinder", title: "Silk Wing", minPoints: 5760, minBugs: 170, rarity: "Zeldzaam", insect: "dragonfly", evolutionLevel: 4, note: "Zachte witte vleugels uit de wereld van zijde." },
  { id: "gevlekte-komkommerkever", name: "Gevlekte komkommerkever", title: "Garden Dots", minPoints: 5770, minBugs: 171, rarity: "Zeldzaam", insect: "beetle", evolutionLevel: 4, note: "Geel tuinschild met duidelijke zwarte stippen." },
  { id: "gestreepte-komkommerkever", name: "Gestreepte komkommerkever", title: "Garden Stripes", minPoints: 5780, minBugs: 172, rarity: "Zeldzaam", insect: "beetle", evolutionLevel: 4, note: "Geel tuinschild met strakke zwarte strepen." },
  { id: "oliekever", name: "Oliekever", title: "Ink Armor", minPoints: 5790, minBugs: 173, rarity: "Zeldzaam", insect: "beetle", evolutionLevel: 4, note: "Zwaar zwart lijf met een olieachtige glans." },
  { id: "groentje", name: "Groentje", title: "Emerald Leaf", minPoints: 5800, minBugs: 174, rarity: "Zeldzaam", insect: "dragonfly", evolutionLevel: 4, note: "Groene vleugels verdwijnen tussen verse bladeren." },
  { id: "heideblauwtje", name: "Heideblauwtje", title: "Heath Azure", minPoints: 5810, minBugs: 175, rarity: "Zeldzaam", insect: "dragonfly", evolutionLevel: 4, note: "Helderblauw accent boven paarse heide." },
  { id: "grote-weerschijnvlinder", name: "Grote weerschijnvlinder", title: "Purple Flash", minPoints: 5820, minBugs: 176, rarity: "Episch", insect: "dragonfly", evolutionLevel: 4, note: "Donkere vleugels flitsen paars in het licht." },
  { id: "bruin-zandoogje", name: "Bruin zandoogje", title: "Meadow Eye", minPoints: 5830, minBugs: 177, rarity: "Gewoon", insect: "dragonfly", evolutionLevel: 3, note: "Warme bruintinten met kleine oogvlekken." },
  { id: "kraamwebspin", name: "Kraamwebspin", title: "Web Guardian", minPoints: 5840, minBugs: 178, rarity: "Zeldzaam", insect: "crawler", evolutionLevel: 4, note: "Waakzame langpoot die haar web bewaakt." },
  { id: "groene-krabspin", name: "Groene krabspin", title: "Leaf Ambush", minPoints: 5850, minBugs: 179, rarity: "Zeldzaam", insect: "crawler", evolutionLevel: 4, note: "Groene hinderlaag met zijwaartse krabpoten." },
  { id: "honingbij", name: "Honingbij", title: "Hive Worker", minPoints: 5860, minBugs: 180, rarity: "Gewoon", insect: "dragonfly", evolutionLevel: 3, note: "Onmisbare werker met een herkenbaar streeppatroon." },
  { id: "dambordvlieg", name: "Dambordvlieg", title: "Grid Wing", minPoints: 5870, minBugs: 181, rarity: "Gewoon", insect: "dragonfly", evolutionLevel: 3, note: "Grijs patroon als een klein dambord." },
  { id: "ligusterpijlstaart", name: "Ligusterpijlstaart", title: "Night Rocket", minPoints: 5880, minBugs: 182, rarity: "Episch", insect: "dragonfly", evolutionLevel: 4, note: "Gestroomlijnde nachtvlinder met scherpe lijnen." },
  { id: "dorbladbidsprinkhaan", name: "Dorbladbidsprinkhaan", title: "Dead Leaf Blade", minPoints: 5890, minBugs: 183, rarity: "Legendarisch", insect: "grasshopper", evolutionLevel: 5, note: "Bijna onzichtbaar tussen droge bladeren." },
  { id: "roze-sprinkhaan", name: "Roze sprinkhaan", title: "Pink Hopper", minPoints: 5900, minBugs: 184, rarity: "Episch", insect: "grasshopper", evolutionLevel: 4, note: "Onverwacht roze en daardoor direct bijzonder." },
  { id: "gouden-vogelvlinder", name: "Gouden vogelvlinder", title: "Golden Flight", minPoints: 5910, minBugs: 185, rarity: "Legendarisch", insect: "dragonfly", evolutionLevel: 5, note: "Grote goudgele vleugels met koninklijke lijnen." },
  { id: "pauwoogpijlstaart", name: "Pauwoogpijlstaart", title: "Hidden Eyes", minPoints: 5920, minBugs: 186, rarity: "Episch", insect: "dragonfly", evolutionLevel: 4, note: "Verborgen oogvlekken verschijnen bij gevaar." },
  { id: "smaragd-springspin", name: "Smaragd-springspin", title: "Emerald Jumper", minPoints: 5930, minBugs: 187, rarity: "Episch", insect: "crawler", evolutionLevel: 4, note: "Metallic groen en klaar voor een precieze sprong." },
  { id: "papiervisje", name: "Papiervisje", title: "Paper Runner", minPoints: 0, minBugs: 0, rarity: "Gewoon", insect: "larva", evolutionLevel: 3, note: "Razendsnelle bewoner van warme, droge hoekjes.", unlockMode: "drop" },
  { id: "ovenvisje", name: "Ovenvisje", title: "Heat Skater", minPoints: 0, minBugs: 0, rarity: "Zeldzaam", insect: "larva", evolutionLevel: 4, note: "Glanzende warmteliefhebber met lange sprieten.", unlockMode: "drop" },
  { id: "bedwants", name: "Bedwants", title: "Night Hitchhiker", minPoints: 0, minBugs: 0, rarity: "Gewoon", insect: "beetle", evolutionLevel: 3, note: "Platte nachtelijke verstekeling uit kieren en bagage.", unlockMode: "drop" },
  { id: "varenrouwmug", name: "Varenrouwmug", title: "Potgrond Pilot", minPoints: 0, minBugs: 0, rarity: "Gewoon", insect: "dragonfly", evolutionLevel: 3, note: "Kleine donkere vlieger rond vochtige potgrond.", unlockMode: "drop" },
  { id: "trips", name: "Trips", title: "Leaf Scraper", minPoints: 0, minBugs: 0, rarity: "Gewoon", insect: "larva", evolutionLevel: 3, note: "Smalle plantenscanner die zilveren sporen achterlaat.", unlockMode: "drop" },
  { id: "spintmijt", name: "Spintmijt", title: "Micro Webber", minPoints: 0, minBugs: 0, rarity: "Zeldzaam", insect: "crawler", evolutionLevel: 4, note: "Miniwever tussen bladnerven en fijne draadjes.", unlockMode: "drop" },
  { id: "wolluis", name: "Wolluis", title: "Cotton Crawler", minPoints: 0, minBugs: 0, rarity: "Zeldzaam", insect: "larva", evolutionLevel: 4, note: "Witte pluizenbol die zich op kamerplanten verstopt.", unlockMode: "drop" },
  { id: "schildluis", name: "Schildluis", title: "Leaf Shield", minPoints: 0, minBugs: 0, rarity: "Gewoon", insect: "beetle", evolutionLevel: 3, note: "Klein plantschild dat bijna op een bobbeltje lijkt.", unlockMode: "drop" },
  { id: "grote-huisspin", name: "Grote huisspin", title: "Hallway Hunter", minPoints: 0, minBugs: 0, rarity: "Zeldzaam", insect: "crawler", evolutionLevel: 4, note: "Lange snelle jager uit schuren en donkere kamers.", unlockMode: "drop" },
  { id: "trilspin", name: "Trilspin", title: "Corner Shaker", minPoints: 0, minBugs: 0, rarity: "Gewoon", insect: "crawler", evolutionLevel: 3, note: "Ultradunne hoekbewoner die zijn web laat trillen.", unlockMode: "drop" },
  { id: "klein-koolwitje", name: "Klein koolwitje", title: "Garden White", minPoints: 0, minBugs: 0, rarity: "Gewoon", insect: "dragonfly", evolutionLevel: 3, note: "Bekende witte tuinvlinder met donkere vleugelpunt.", unlockMode: "drop" },
  { id: "klein-geaderd-witje", name: "Klein geaderd witje", title: "Veined White", minPoints: 0, minBugs: 0, rarity: "Zeldzaam", insect: "dragonfly", evolutionLevel: 4, note: "Licht witje met duidelijk getekende aders.", unlockMode: "drop" },
  { id: "citroenvlinder", name: "Citroenvlinder", title: "Lemon Wing", minPoints: 0, minBugs: 0, rarity: "Episch", insect: "dragonfly", evolutionLevel: 4, note: "Felgele voorjaarsvleugel met bladvormig silhouet.", unlockMode: "drop" },
  { id: "bont-zandoogje", name: "Bont zandoogje", title: "Woodland Eyes", minPoints: 0, minBugs: 0, rarity: "Zeldzaam", insect: "dragonfly", evolutionLevel: 4, note: "Bruine bosvlinder met lichte vlekken en oogjes.", unlockMode: "drop" },
  { id: "icarusblauwtje", name: "Icarusblauwtje", title: "Meadow Azure", minPoints: 0, minBugs: 0, rarity: "Legendarisch", insect: "dragonfly", evolutionLevel: 5, note: "Helderblauwe graslandparel met fijne vleugelrand.", unlockMode: "drop" },
  { id: "kleine-vos", name: "Kleine vos", title: "Ember Wing", minPoints: 0, minBugs: 0, rarity: "Legendarisch", insect: "dragonfly", evolutionLevel: 5, note: "Oranje klassieker met blauwe maantjes langs de rand.", unlockMode: "drop" },
  { id: "landkaartje", name: "Landkaartje", title: "Map Wing", minPoints: 0, minBugs: 0, rarity: "Episch", insect: "dragonfly", evolutionLevel: 4, note: "Seizoensvlinder met een opvallend landkaartpatroon.", unlockMode: "drop" },
  { id: "boomblauwtje", name: "Boomblauwtje", title: "Canopy Blue", minPoints: 0, minBugs: 0, rarity: "Episch", insect: "dragonfly", evolutionLevel: 4, note: "Zachtblauwe vlinder die vaak rond struiken vliegt.", unlockMode: "drop" },
  { id: "springstaart", name: "Springstaart", title: "Soil Jumper", minPoints: 0, minBugs: 0, rarity: "Gewoon", insect: "grasshopper", evolutionLevel: 3, note: "Piepkleine bodemspringer uit vochtige potten en aarde.", unlockMode: "drop" },
  { id: "miljoenpoot", name: "Miljoenpoot", title: "Coil Walker", minPoints: 0, minBugs: 0, rarity: "Zeldzaam", insect: "crawler", evolutionLevel: 4, note: "Rustige veelpoot die zich bij gevaar oprolt.", unlockMode: "drop" },
  { id: "kelderpissebed", name: "Kelderpissebed", title: "Cellar Roller", minPoints: 0, minBugs: 0, rarity: "Gewoon", insect: "crawler", evolutionLevel: 3, note: "Grijze vochtzoeker uit kelders en onder stenen.", unlockMode: "drop" },
  { id: "oprolpissebed", name: "Oprolpissebed", title: "Armor Ball", minPoints: 0, minBugs: 0, rarity: "Zeldzaam", insect: "crawler", evolutionLevel: 4, note: "Compact pantser dat verandert in een bijna perfecte bal.", unlockMode: "drop" },
  { id: "buxusmot", name: "Buxusmot", title: "Hedge Invader", minPoints: 0, minBugs: 0, rarity: "Episch", insect: "dragonfly", evolutionLevel: 4, note: "Witbruine nachtvlinder die bij buxushagen opvalt.", unlockMode: "drop" },
  { id: "buxusrups", name: "Buxusrups", title: "Hedge Stripper", minPoints: 0, minBugs: 0, rarity: "Zeldzaam", insect: "larva", evolutionLevel: 4, note: "Groenzwarte rups die buxusbladeren snel opeet.", unlockMode: "drop" },
  { id: "leliehaantje", name: "Leliehaantje", title: "Scarlet Leaf", minPoints: 0, minBugs: 0, rarity: "Episch", insect: "beetle", evolutionLevel: 4, note: "Lakrode tuinkever die direct tussen groene bladeren knalt.", unlockMode: "drop" },
  { id: "engerling", name: "Engerling", title: "Root Grub", minPoints: 0, minBugs: 0, rarity: "Gewoon", insect: "larva", evolutionLevel: 3, note: "C-vormige keverlarve die onder gras en aarde leeft.", unlockMode: "drop" },
  { id: "emelt", name: "Emelt", title: "Lawn Larva", minPoints: 0, minBugs: 0, rarity: "Gewoon", insect: "larva", evolutionLevel: 3, note: "Pootloze langpootmuglarve uit gazon en bodem.", unlockMode: "drop" },
  { id: "gamma-uil", name: "Gamma-uil", title: "Silver Mark", minPoints: 0, minBugs: 0, rarity: "Episch", insect: "dragonfly", evolutionLevel: 4, note: "Bruine trekvlinder met een zilveren gammateken.", unlockMode: "drop" },
  { id: "huismoeder", name: "Huismoeder", title: "Porch Moth", minPoints: 0, minBugs: 0, rarity: "Zeldzaam", insect: "dragonfly", evolutionLevel: 4, note: "Grote bruine nachtvlinder die vaak bij buitenlampen zit.", unlockMode: "drop" },
  { id: "agaatvlinder", name: "Agaatvlinder", title: "Marbled Wing", minPoints: 0, minBugs: 0, rarity: "Episch", insect: "dragonfly", evolutionLevel: 4, note: "Nachtvlinder met golvende lijnen als gepolijste steen.", unlockMode: "drop" },
  { id: "windevedermot", name: "Windevedermot", title: "Feather Wing", minPoints: 0, minBugs: 0, rarity: "Episch", insect: "dragonfly", evolutionLevel: 4, note: "Slanke mot die zijn vleugels als een T uitstrekt.", unlockMode: "drop" },
  { id: "jakobsvlinder", name: "Jakobsvlinder", title: "Crimson Warning", minPoints: 0, minBugs: 0, rarity: "Legendarisch", insect: "dragonfly", evolutionLevel: 5, note: "Zwartrode waarschuwingsvlinder met krachtige kleuren.", unlockMode: "drop" },
  { id: "jakobsvlinderrups", name: "Jakobsvlinderrups", title: "Stripe Warning", minPoints: 0, minBugs: 0, rarity: "Episch", insect: "larva", evolutionLevel: 4, note: "Geelzwarte rups die zijn giftige menu duidelijk toont.", unlockMode: "drop" },
  { id: "distelvlinder", name: "Distelvlinder", title: "Global Traveler", minPoints: 0, minBugs: 0, rarity: "Legendarisch", insect: "dragonfly", evolutionLevel: 5, note: "Oranje wereldreiziger met sterk zwart-wit patroon.", unlockMode: "drop" },
  { id: "groot-koolwitje", name: "Groot koolwitje", title: "Bold White", minPoints: 0, minBugs: 0, rarity: "Zeldzaam", insect: "dragonfly", evolutionLevel: 4, note: "Groot wit silhouet met brede donkere vleugelpunten.", unlockMode: "drop" },
  { id: "hooibeestje", name: "Hooibeestje", title: "Grassland Eye", minPoints: 0, minBugs: 0, rarity: "Zeldzaam", insect: "dragonfly", evolutionLevel: 4, note: "Kleine bruine grasvlinder met een helder oogvlekje.", unlockMode: "drop" },
  { id: "koevinkje", name: "Koevinkje", title: "Shadow Meadow", minPoints: 0, minBugs: 0, rarity: "Episch", insect: "dragonfly", evolutionLevel: 4, note: "Donkere graslandvlinder met subtiele oogjes.", unlockMode: "drop" },
  { id: "geelpoothoornaar", name: "Geelpoothoornaar", title: "Yellow Leg Alert", minPoints: 0, minBugs: 0, rarity: "Legendarisch", insect: "dragonfly", evolutionLevel: 5, note: "Donkere hoornaar met opvallend gele uiteinden aan de poten.", unlockMode: "drop" },
  { id: "daas", name: "Daas", title: "Heavy Biter", minPoints: 0, minBugs: 0, rarity: "Zeldzaam", insect: "dragonfly", evolutionLevel: 4, note: "Stevige vlieg met grote ogen en een pijnlijke reputatie.", unlockMode: "drop" },
  { id: "stadsreus", name: "Stadsreus", title: "Urban Hover", minPoints: 0, minBugs: 0, rarity: "Episch", insect: "dragonfly", evolutionLevel: 4, note: "Enorme zweefvlieg die op een hoornaar lijkt.", unlockMode: "drop" },
  { id: "bijvlieg", name: "Bijvlieg", title: "Bee Mimic", minPoints: 0, minBugs: 0, rarity: "Zeldzaam", insect: "dragonfly", evolutionLevel: 4, note: "Pluizige zweefvlieg in overtuigende bijenvermomming.", unlockMode: "drop" },
  { id: "rosse-metselbij", name: "Rosse metselbij", title: "Brick Nest Builder", minPoints: 0, minBugs: 0, rarity: "Episch", insect: "dragonfly", evolutionLevel: 4, note: "Roodharige solitaire bij die nestkamers dichtmetselt.", unlockMode: "drop" },
  { id: "blauwzwarte-houtbij", name: "Blauwzwarte houtbij", title: "Midnight Carpenter", minPoints: 0, minBugs: 0, rarity: "Legendarisch", insect: "dragonfly", evolutionLevel: 5, note: "Grote donkere bij met blauw glanzende vleugels.", unlockMode: "drop" },
  { id: "gewone-wolfspin", name: "Gewone wolfspin", title: "Ground Stalker", minPoints: 0, minBugs: 0, rarity: "Zeldzaam", insect: "crawler", evolutionLevel: 4, note: "Snelle bodemjager die zonder vangweb rondsluipt.", unlockMode: "drop" },
  { id: "venstersectorspin", name: "Venstersectorspin", title: "Window Webber", minPoints: 0, minBugs: 0, rarity: "Episch", insect: "crawler", evolutionLevel: 4, note: "Bouwt een herkenbaar web bij ramen en gevelhoeken.", unlockMode: "drop" },
  { id: "grote-wegslak", name: "Grote wegslak", title: "Night Slider", minPoints: 0, minBugs: 0, rarity: "Gewoon", insect: "crawler", evolutionLevel: 3, note: "Grote donkere tuinreiziger die een glanzend spoor achterlaat.", unlockMode: "drop" },
  { id: "segrijnslak", name: "Segrijnslak", title: "Garden Spiral", minPoints: 0, minBugs: 0, rarity: "Zeldzaam", insect: "crawler", evolutionLevel: 4, note: "Bekende tuinslak met een warmbruin spiraalhuis.", unlockMode: "drop" },
  { id: "regenworm", name: "Regenworm", title: "Soil Engineer", minPoints: 0, minBugs: 0, rarity: "Gewoon", insect: "larva", evolutionLevel: 3, note: "Onmisbare bodembouwer die gangen en lucht maakt.", unlockMode: "drop" },
  { id: "broodkever", name: "Broodkever", title: "Pantry Driller", minPoints: 0, minBugs: 0, rarity: "Gewoon", insect: "beetle", evolutionLevel: 3, note: "Kleine bruine voorraadkever met een strak cilindervormig schild.", unlockMode: "drop" },
  { id: "gewone-houtwormkever", name: "Gewone houtwormkever", title: "Timber Tunneler", minPoints: 0, minBugs: 0, rarity: "Gewoon", insect: "beetle", evolutionLevel: 3, note: "Slanke houtkever die zich jarenlang verborgen kan houden.", unlockMode: "drop" },
  { id: "gewone-kogelspin", name: "Gewone kogelspin", title: "Speckled Webber", minPoints: 0, minBugs: 0, rarity: "Zeldzaam", insect: "crawler", evolutionLevel: 4, note: "Fijngebouwde huisspin met een opvallend gemarmerd achterlijf.", unlockMode: "drop" },
  { id: "kruipende-kogelspin", name: "Kruipende kogelspin", title: "Cellar Prowler", minPoints: 0, minBugs: 0, rarity: "Zeldzaam", insect: "crawler", evolutionLevel: 4, note: "Compacte nachtelijke jager met een donker fluwelen silhouet.", unlockMode: "drop" },
  { id: "nachtkaardespin", name: "Nachtkaardespin", title: "Night Sigil", minPoints: 0, minBugs: 0, rarity: "Episch", insect: "crawler", evolutionLevel: 4, note: "Grote wielwebspin met een bladachtig patroon op haar achterlijf.", unlockMode: "drop" },
  { id: "argusvlinder", name: "Argusvlinder", title: "Amber Watcher", minPoints: 0, minBugs: 0, rarity: "Episch", insect: "dragonfly", evolutionLevel: 4, note: "Warmoranje graslandvlinder met een rij scherpe oogvlekken.", unlockMode: "drop" },
  { id: "spaanse-vlag", name: "Spaanse vlag", title: "Crimson Banner", minPoints: 0, minBugs: 0, rarity: "Episch", insect: "dragonfly", evolutionLevel: 4, note: "Zwart-witte dagactieve nachtvlinder met felrode achtervleugels.", unlockMode: "drop" },
  { id: "weidebeekjuffer", name: "Weidebeekjuffer", title: "River Dancer", minPoints: 0, minBugs: 0, rarity: "Episch", insect: "dragonfly", evolutionLevel: 4, note: "Metaalblauwe beekjuffer met een brede donkere band over de vleugels.", unlockMode: "drop" },
  { id: "steenhommel", name: "Steenhommel", title: "Ember Tail", minPoints: 0, minBugs: 0, rarity: "Zeldzaam", insect: "dragonfly", evolutionLevel: 4, note: "Fluweelzwarte hommel met een opvallend oranjerode achterlijfspunt.", unlockMode: "drop" },
  { id: "aardhommel", name: "Aardhommel", title: "Burrow Scout", minPoints: 0, minBugs: 0, rarity: "Gewoon", insect: "dragonfly", evolutionLevel: 3, note: "Grote zwart-gele hommel die vaak laag bij de grond naar een nestplek zoekt.", unlockMode: "drop" },
  { id: "akkerhommel", name: "Akkerhommel", title: "Copper Forager", minPoints: 0, minBugs: 0, rarity: "Gewoon", insect: "dragonfly", evolutionLevel: 3, note: "Rosbruine tuinbezoeker die van het vroege voorjaar tot diep in de herfst vliegt.", unlockMode: "drop" },
  { id: "boomhommel", name: "Boomhommel", title: "Canopy Builder", minPoints: 0, minBugs: 0, rarity: "Zeldzaam", insect: "dragonfly", evolutionLevel: 4, note: "Bruinrug met witte staart die graag nestelt in boomholtes en nestkastjes.", unlockMode: "drop" },
  { id: "heidehommel", name: "Heidehommel", title: "Heather Whisper", minPoints: 0, minBugs: 0, rarity: "Zeldzaam", insect: "dragonfly", evolutionLevel: 4, note: "Licht behaarde hommel die tussen heide, klaver en andere lage bloemen foerageert.", unlockMode: "drop" },
  { id: "tuinhommel", name: "Tuinhommel", title: "Long Tongue", minPoints: 0, minBugs: 0, rarity: "Episch", insect: "dragonfly", evolutionLevel: 4, note: "Langgerekte zwart-gele hommel met een lange tong voor diepe bloemen.", unlockMode: "drop" },
  { id: "weidehommel", name: "Weidehommel", title: "Meadow Spark", minPoints: 0, minBugs: 0, rarity: "Episch", insect: "dragonfly", evolutionLevel: 4, note: "Kleine vroege hommel met gele banden en een helder oranjerode staart.", unlockMode: "drop" },
  { id: "veldhommel", name: "Veldhommel", title: "White Tail", minPoints: 0, minBugs: 0, rarity: "Zeldzaam", insect: "dragonfly", evolutionLevel: 4, note: "Zwart-gele veldbezoeker met een helder witte staart en een stevige bouw.", unlockMode: "drop" },
  { id: "muskusboktor", name: "Muskusboktor", title: "Emerald Antenna", minPoints: 0, minBugs: 0, rarity: "Legendarisch", insect: "beetle", evolutionLevel: 5, note: "Grote metaalgroene boktor met uitzonderlijk lange antennes.", unlockMode: "drop" },
  { id: "eikenpage", name: "Eikenpage", title: "Oak Shadow", minPoints: 0, minBugs: 0, rarity: "Episch", insect: "dragonfly", evolutionLevel: 4, note: "Donkere boomtopvlinder met een oranje hoek en fijne staartjes.", unlockMode: "drop" },
  ...bugDexExpansionEntries
];

export const bugDexFacts: Record<string, string> = {
  "zilvervisje": "Zilvervisjes houden van donkere, vochtige plekken en rennen weg zodra het licht aangaat.",
  "fruitvlieg": "Fruitvliegen kunnen in een warme keuken razendsnel meerdere generaties krijgen.",
  "bladluis": "Bladluizen drinken plantensap en laten vaak kleverige honingdauw achter.",
  "mug": "Alleen vrouwelijke muggen steken; zij gebruiken bloed voor hun eitjes.",
  "mot": "Veel motten navigeren op licht, waardoor lampen ze flink in de war brengen.",
  "mier": "Mieren laten geursporen achter zodat de kolonie dezelfde route kan volgen.",
  "vlo": "Vlooien springen vele keren hun eigen lichaamslengte dankzij krachtige achterpoten.",
  "pissebed": "Pissebedden zijn eigenlijk kreeftachtigen en ademen via kieuwachtige structuren.",
  "stinkwants": "Stinkwantsen gebruiken geur als verdediging wanneer ze zich bedreigd voelen.",
  "snuitkever": "Snuitkevers hebben een lange snuit waarmee ze in planten kunnen boren.",
  "lieveheersbeestje": "Lieveheersbeestjes eten graag bladluizen en zijn daardoor nuttige tuinhelpers.",
  "kakkerlak": "Kakkerlakken zijn taai omdat ze snel schuilen en weinig nodig hebben om te overleven.",
  "oorworm": "Oorwormen gebruiken hun tangetjes vooral voor verdediging en onderlinge duwtjes.",
  "boktor": "Boktorren vallen op door lange antennes die soms langer zijn dan hun lijf.",
  "tapijtkever": "Tapijtkeverlarven knabbelen aan vezels zoals wol, veren en oude textielresten.",
  "roofwants": "Roofwantsen jagen op andere insecten met een scherpe zuigsnuit.",
  "duizendpoot": "Duizendpoten hebben geen duizend poten, maar wel genoeg om soepel te sprinten.",
  "sprinkhaan": "Sprinkhanen maken grote sprongen door hun gespierde achterpoten.",
  "wesp": "Wespen herkennen geursporen en keren daardoor vaak terug naar voedselplekken.",
  "hoornaar": "Hoornaars zijn grote wespen en jagen vaak op andere insecten.",
  "schorpioen": "Schorpioenen lichten op onder uv-licht door stoffen in hun pantser.",
  "termiet": "Termieten bouwen complexe kolonies en recyclen hard plantmateriaal.",
  "mestkever": "Mestkevers rollen mestballen die dienen als voedsel of broedkamer.",
  "wandelende-tak": "Wandelende takken lijken op twijgen en blijven vaak doodstil om niet op te vallen.",
  "vogelspin": "Vogelspinnen voelen trillingen via gevoelige haren op hun poten.",
  "reuzenkakkerlak": "Sommige reuzenkakkerlakken sissen door lucht uit hun ademopeningen te persen.",
  "reuzen-duizendpoot": "Reuzenduizendpoten zijn snelle jagers met giftige kaken aan de voorkant.",
  "neushoornkever": "Mannetjesneushoornkevers gebruiken hun hoorn om rivalen weg te duwen.",
  "atlaskever": "Atlaskevers zijn zware tropische kevers met indrukwekkende hoorns.",
  "herculeskever": "Herculeskevers behoren tot de grootste kevers ter wereld.",
  "goliathkever": "Goliathkevers zijn massieve kevers die als larve al flink zwaar kunnen worden.",
  "motmug": "Motmuggen hebben harige vleugels en zitten vaak bij vochtige afvoerplekken.",
  "langpootmug": "Langpootmuggen zien eruit als enorme muggen, maar steken niet.",
  "faraomier": "Faraomieren kunnen meerdere koninginnen hebben, waardoor nesten lastig verdwijnen.",
  "boekluis": "Boekluizen eten schimmels en houden van papierige, vochtige hoekjes.",
  "stofluis": "Stofluizen zijn klein en verraden vaak dat ergens te veel vocht zit.",
  "teek": "Teken wachten vaak op gras of struiken tot een gastheer langsloopt.",
  "fluweelmijt": "Fluweelmijten vallen op door hun felrode, fluweelachtige lijf.",
  "schildwants": "Schildwantsen danken hun naam aan hun schildvormige rug.",
  "houtmier": "Houtmieren maken grote nesten en werken met strakke taakverdeling.",
  "kniptor": "Kniptorren kunnen zichzelf met een klikbeweging weer rechtop schieten.",
  "loopkever": "Loopkevers zijn snelle bodemjagers die vaak 's nachts actief zijn.",
  "waterkever": "Waterkevers nemen lucht mee onder hun schild wanneer ze duiken.",
  "schrijvertje": "Schrijvertjes draaien rondjes op water en zien tegelijk boven en onder water.",
  "schaatsenrijder": "Schaatsenrijders glijden over water door oppervlaktespanning te gebruiken.",
  "goudtor": "Goudtorren hebben vaak een metaalglans die verandert met het licht.",
  "tijgerkever": "Tijgerkevers zijn snelle jagers met opvallend grote kaken.",
  "doodgraver": "Doodgravers begraven kleine dode dieren als voedsel voor hun larven.",
  "waterschorpioen": "Waterschorpioenen ademen via een lange buis aan hun achterlijf.",
  "bidsprinkhaan": "Bidsprinkhanen slaan razendsnel toe met hun gevouwen grijppoten.",
  "wandelend-blad": "Wandelende bladeren lijken op blaadjes, inclusief nerven en rafelrandjes.",
  "wespspin": "Wespspinnen hebben gele strepen die lijken op een waarschuwing.",
  "kruisspin": "Kruisspinnen bouwen ronde webben en wachten in of naast het midden.",
  "springspin": "Springspinnen hebben grote ogen en bespringen prooi heel precies.",
  "libel": "Libellen kunnen stilhangen, achteruit vliegen en razendsnel draaien.",
  "waterjuffer": "Waterjuffers zijn slanker dan libellen en houden hun vleugels vaak dicht.",
  "gaasvlieg": "Gaasvliegen hebben fijne, doorzichtige vleugels met een netpatroon.",
  "doodshoofdvlinder": "Doodshoofdvlinders hebben een tekening op hun rug die op een schedel lijkt.",
  "kolibrievlinder": "Kolibrievlinders drinken nectar terwijl ze als een kolibrie blijven hangen.",
  "koninginnenpage": "De koninginnenpage is een grote vlinder met sierlijke staartpunten.",
  "atalanta": "Atalanta's zijn trekvlinders die grote afstanden kunnen afleggen.",
  "dagpauwoog": "Dagpauwogen hebben oogvlekken die roofdieren kunnen afschrikken.",
  "eikenprocessierups": "Eikenprocessierupsen lopen vaak in lange rijen over eikenstammen.",
  "pijlstaartrups": "Pijlstaartrupsen hebben een opvallend staartpuntje aan hun achterlijf.",
  "cicade": "Cicaden maken geluid met trilorganen, niet door vleugels te wrijven.",
  "schuimcicade": "Schuimcicadelarven verstoppen zich in schuim dat lijkt op spuug.",
  "vliegend-hert": "Vliegende herten hebben enorme kaken die vooral dienen bij gevechten tussen mannetjes.",
  "juweelkever": "Juweelkevers staan bekend om hun felle, metaalachtige kleuren.",
  "orchidee-bidsprinkhaan": "Orchidee-bidsprinkhanen lijken op bloemen om prooi dichterbij te lokken.",
  "pauwspin": "Pauwspinnen dansen met kleurrijke flapjes om indruk te maken.",
  "juweelwesp": "Juweelwespen glanzen metallic groen en blauw als kleine edelstenen.",
  "goudschildkever": "Goudschildkevers kunnen glanzen alsof ze een gouden schild dragen.",
  "harlekijnwants": "Harlekijnwantsen vallen op met felle patronen die waarschuwingen lijken.",
  "lantaarnvlieg": "Lantaarnvliegen hebben vreemde kopvormen en vaak opvallende vleugeltekeningen.",
  "vioolspin": "Vioolspinnen danken hun naam aan de vioolachtige tekening op hun lichaam.",
  "gespikkelde-houtvlinder": "Gespikkelde houtvlinders hebben een patroon dat lijkt op boomschors en vlekjes.",
  "zebra-springspin": "Zebra-springspinnen zijn klein, gestreept en nieuwsgierig naar beweging.",
  "smaragdlibel": "Smaragdlibellen hebben een groene glans die in zonlicht sterk opvalt.",
  "glasvleugelvlinder": "Glasvleugelvlinders hebben doorzichtige vleugels waardoor ze deels verdwijnen.",
  "komeetmot": "Komeetmotten hebben lange staarten aan hun vleugels als een spoor.",
  "maanmot": "Maanmotten hebben zachte groene vleugels en lange sierlijke staarten.",
  "atlasvlinder": "Atlasvlinders zijn enorme vlinders met vleugelpunten die op slangenkoppen lijken.",
  "rozekever": "Rozekevers glanzen vaak groen, koper of rozerood afhankelijk van het licht.",
  "kardinaalkever": "Kardinaalkevers vallen op door hun felle rode kleur.",
  "vuurwants": "Vuurwantsen verzamelen vaak in groepen op warme stenen of boomstammen.",
  "sabelsprinkhaan": "Sabelsprinkhanen hebben lange antennes en stevige springpoten.",
  "mierenleeuw": "Mierenleeuwlarven maken trechterkuilen waarin kleine prooien wegglijden.",
  "dobsonvlieg": "Mannelijke dobsonvliegen hebben enorme kaken die vooral indruk maken.",
  "helikopterjuffer": "Helikopterjuffers hebben brede vleugels en een sierlijke, zwevende vlucht.",
  "spookinsect": "Spookinsecten vertrouwen op camouflage en lijken op droge takjes of bladeren.",
  "bladpootwants": "Bladpootwantsen hebben verbrede achterpoten die op kleine blaadjes lijken.",
  "assassin-bug": "Assassin bugs zijn sluipende jagers die prooi met een snuit prikken.",
  "tijgermug": "Tijgermuggen herken je aan hun zwart-witte strepen.",
  "dolksteekwesp": "Dolksteekwespen jagen vaak op larven van kevers in de bodem.",
  "roofvlieg": "Roofvliegen vangen andere insecten in de lucht met sterke poten.",
  "kameelhalsvlieg": "Kameelhalsvliegen hebben een lange halsachtige borst en bewegen opvallend hoekig.",
  "zweefvlieg": "Zweefvliegen lijken op wespen, maar zijn onschuldige bloemenbezoekers.",
  "goudwesp": "Goudwespen hebben een harde, glanzende buitenkant en rollen zich soms op.",
  "sluipwesp": "Sluipwespen leggen eitjes bij andere insecten en houden plagen in toom.",
  "fluweelmier": "Fluweelmieren zijn eigenlijk wespen; de vrouwtjes hebben geen vleugels.",
  "reuzenwaterwants": "Reuzenwaterwantsen zijn sterke waterrovers die prooi onder water grijpen.",
  "zweepschorpioen": "Zweepschorpioenen hebben geen angel, maar wel een lange zweepstaart.",
  "azuren-waterjuffer": "Azuren waterjuffers vallen op door hun heldere blauwe tekening.",
  "rouwmantelvlinder": "Rouwmantelvlinders hebben donkere vleugels met een lichte rand.",
  "keizersmantel": "Keizersmantels zijn oranje vlinders die graag langs bosranden vliegen.",
  "gouden-tor": "Gouden torren lijken compact, glanzend en bijna gepolijst.",
  "soldaatje": "Soldaatjes zijn zachte kevers die vaak op bloemen zitten.",
  "doodgraverkever": "Doodgraverkevers ruiken aas van ver en werken soms als paar samen.",
  "olifantskever": "Olifantskevers zijn grote neushoornkevers met forse hoorns.",
  "regenboogmestkever": "Regenboogmestkevers combineren mestrollen met felle metaalglans.",
  "titanus-kever": "Titanuskevers zijn reuzenboktorren met een indrukwekkend formaat.",
  "langsprietboktor": "Langsprietboktorren gebruiken hun lange sprieten om omgeving en geur te verkennen.",
  "schildpadkever": "Schildpadkevers hebben een rond schild dat over hun poten valt.",
  "vuurkever": "Vuurkevers dragen felrode schilden die direct opvallen tussen bladeren.",
  "blauwe-ertsbij": "Blauwe ertsbijen hebben een diepe blauwzwarte metaalglans.",
  "wespboktor": "Wespboktorren lijken op wespen, maar zijn kevers met lange sprieten.",
  "groene-zandloopkever": "Groene zandloopkevers sprinten over zandige plekken en jagen op zicht.",
  "lauwstaartwaterjuffer": "Lauwstaartwaterjuffers hebben een slanke bouw en opvallend blauw aan het achterlijf.",
  "roodwitte-celspin": "Roodwitte celspinnen leven vaak verborgen en vallen op door hun contrasterende tekening.",
  "koningin-alexandravlinder": "De Koningin-Alexandravlinder is een van de grootste dagvlinders ter wereld en komt uit Papoea-Nieuw-Guinea.",
  "zonsondergangsmot": "De Madagascan sunset moth heeft iriserende vleugels die kleuren tonen door lichtbreking.",
  "picasso-wants": "De Picasso-wants heeft patronen die bijna geschilderd lijken en roofdieren waarschuwen.",
  "roze-esdoornmot": "De roze esdoornmot valt op door zijn zachte roze en gele kleuren.",
  "giraffekevertje": "Het giraffekevertje uit Madagaskar heeft een extreem lange nek, vooral bij mannetjes.",
  "doornbloembidsprinkhaan": "De doornbloembidsprinkhaan lijkt op een bloem en gebruikt camouflage bij het jagen.",
  "lantaarndrager": "Lantaarndragers hebben een lange kopuitsteeksel en opvallend getekende vleugels.",
  "glorieuze-scarabee": "De glorious scarab heeft metallic groene en zilveren strepen die sterk glanzen.",
  "bromvlieg": "Bromvliegen zijn vaak wat groter en luidruchtiger dan gewone huisvliegen.",
  "dwergcicade": "Dwergcicaden zijn kleine plantensapdrinkers die snel wegspringen bij verstoring.",
  "groene-junikever": "Groene junikevers vallen op door hun groene kleur en zijn vooral actief in warme maanden.",
  "hommel": "Hommels zijn behaarde bijen en belangrijke bestuivers voor bloemen en gewassen.",
  "huisvlieg": "Huisvliegen proeven met hun poten en landen daarom vaak op voedselresten.",
  "kleermot": "Kleermotlarven kunnen schade maken aan wol, veren en andere dierlijke vezels.",
  "meikever": "Meikevers vliegen vooral in het voorjaar en hebben waaiervormige antenneplaatjes.",
  "schorpioenvlieg": "Schorpioenvliegen danken hun naam aan het gekromde achterlijf van sommige mannetjes.",
  "voorraadmot": "Voorraadmotten leggen eitjes bij droge voedselvoorraden zoals meel, graan of noten.",
  "whitefly": "Whiteflies zitten vaak aan de onderkant van bladeren en zuigen plantensap.",
  "witte-tijger": "De naam Witte tijger verwijst hier naar het lichte, gestreepte patroon van de BugDex-afbeelding.",
  "papiervisje": "Papiervisjes lijken op zilvervisjes, maar houden juist van warmere en drogere gebouwen.",
  "ovenvisje": "Ovenvisjes zoeken zeer warme plekken op, bijvoorbeeld rond verwarmingsruimtes en leidingen.",
  "bedwants": "Bedwantsen verstoppen zich overdag in smalle kieren en komen meestal in de nacht tevoorschijn.",
  "varenrouwmug": "Varenrouwmuglarven leven in vochtige potgrond en eten vooral schimmels en zacht plantenmateriaal.",
  "trips": "Tripsen zijn smalle insecten die bladeren beschadigen door plantencellen leeg te schrapen.",
  "spintmijt": "Spintmijten zijn spinachtigen en maken bij grotere aantallen fijne webjes rond bladeren.",
  "wolluis": "Wolluizen beschermen zich met een witte waslaag die eruitziet als kleine plukjes katoen.",
  "schildluis": "Schildluizen zitten vaak onbeweeglijk op stengels en bladeren onder een hard beschermend schildje.",
  "grote-huisspin": "Grote huisspinnen rennen snel, maar gebruiken meestal een trechterweb als vaste schuilplaats.",
  "trilspin": "Trilspinnen laten hun lichaam en web snel trillen wanneer ze worden verstoord.",
  "klein-koolwitje": "Kleine koolwitjes zijn veel in tuinen te zien en leggen eitjes op planten uit de koolfamilie.",
  "klein-geaderd-witje": "Bij het klein geaderd witje zijn de donkere aders vooral aan de onderkant goed zichtbaar.",
  "citroenvlinder": "Citroenvlinders overwinteren als volwassen vlinder en kunnen vroeg in het voorjaar vliegen.",
  "bont-zandoogje": "Bonte zandoogjes verdedigen zonnige plekjes langs bosranden en tussen struiken.",
  "icarusblauwtje": "Mannetjes van het icarusblauwtje hebben opvallend blauwe bovenvleugels.",
  "kleine-vos": "Kleine vossen overwinteren geregeld in schuren, zolders en andere koele gebouwen.",
  "landkaartje": "Het landkaartje heeft een voorjaars- en zomervorm die sterk van kleur en patroon verschillen.",
  "boomblauwtje": "Boomblauwtjes vliegen vaak hoger rond struiken en bomen dan veel andere blauwtjes.",
  "springstaart": "Springstaarten gebruiken een gevorkt springorgaan onder hun lichaam om plots weg te schieten.",
  "miljoenpoot": "Miljoenpoten hebben twee paar poten per zichtbaar lichaamssegment en eten vooral dood plantenmateriaal.",
  "kelderpissebed": "Kelderpissebedden zoeken vochtige schuilplekken omdat hun kieuwachtige organen niet mogen uitdrogen.",
  "oprolpissebed": "Oprolpissebedden kunnen kop en poten volledig beschermen door zich tot een bolletje op te rollen.",
  "buxusmot": "Buxusmotten zijn witte nachtvlinders met vaak een brede bruine rand langs de vleugels.",
  "buxusrups": "Buxusrupsen leven tussen spinsel in buxusplanten en kunnen veel blad wegvreten.",
  "leliehaantje": "Leliehaantjes vallen op door hun glanzend rode dekschilden en eten aan leliebladeren.",
  "engerling": "Engerlingen zijn larven van bladsprietkevers en liggen meestal gekromd in een C-vorm.",
  "emelt": "Emelten zijn larven van langpootmuggen en leven vlak onder of op het bodemoppervlak.",
  "gamma-uil": "De gamma-uil dankt zijn naam aan het zilverkleurige teken op iedere voorvleugel.",
  "huismoeder": "Huismoeders rusten overdag verborgen en komen in de avond vaak op licht af.",
  "agaatvlinder": "Agaatvlinders hebben een variabel marmerpatroon van bruine, crème en soms groenige tinten.",
  "windevedermot": "Windevedermotten rollen hun smalle vleugels op en rusten daardoor in een herkenbare T-houding.",
  "jakobsvlinder": "Jakobsvlinders tonen met hun zwartrode kleur dat ze voor veel roofdieren onaantrekkelijk zijn.",
  "jakobsvlinderrups": "Jakobsvlinderrupsen slaan afweerstoffen uit hun waardplant op in hun lichaam.",
  "distelvlinder": "Distelvlinders zijn trekvlinders die ieder jaar vanuit zuidelijkere gebieden naar Nederland vliegen.",
  "groot-koolwitje": "Grote koolwitjes hebben bredere zwarte vleugelpunten dan het kleinere koolwitje.",
  "hooibeestje": "Hooibeestjes rusten bijna altijd met gesloten vleugels en tonen dan hun kleine oogvlek.",
  "koevinkje": "Koevinkjes vliegen laag door ruige graslanden en langs zonnige bosranden.",
  "geelpoothoornaar": "De geelpoothoornaar is donker van kleur en heeft opvallend gele uiteinden aan de poten.",
  "daas": "Dazen gebruiken hun grote facetogen om bewegende dieren en mensen snel te vinden.",
  "stadsreus": "De stadsreus is een grote zweefvlieg die door zijn tekening sterk op een hoornaar lijkt.",
  "bijvlieg": "Bijvliegen bootsen het uiterlijk van bijen na, maar hebben als vliegen slechts één paar vleugels.",
  "rosse-metselbij": "Rosse metselbijen maken afzonderlijke broedcellen en sluiten die af met modder.",
  "blauwzwarte-houtbij": "Blauwzwarte houtbijen knagen nestgangen in dood of verweerd hout.",
  "gewone-wolfspin": "Wolfspinnen jagen lopend op prooi en bouwen geen vangweb om voedsel te vangen.",
  "venstersectorspin": "Venstersectorspinnen maken vaak een web met een ontbrekende sector en een signaaldraad naar hun schuilplaats.",
  "grote-wegslak": "Grote wegslakken zijn vooral bij vochtig weer en in de schemering actief.",
  "segrijnslak": "Segrijnslakken hebben meestal een bruin gemarmerd huis met een duidelijke spiraal.",
  "regenworm": "Regenwormen mengen organisch materiaal door de bodem en maken gangen waardoor lucht en water doordringen.",
  "zadelrups": "Zadelrupsen vallen op door hun groene lichaam met een donker zadelvormig vlekpatroon.",
  "reuzenpantervlinder": "Reuzenpantervlinders hebben opvallende donkere vlekken die doen denken aan een pantertekening.",
  "monarchvlinder": "Monarchvlinders gebruiken gifstoffen uit hun waardplant als bescherming tegen veel roofdieren.",
  "zakdrager": "Zakdragerlarven bouwen een draagbaar kokertje van zijde en plantenresten.",
  "gehakkelde-aurelia": "De gehakkelde aurelia heeft diep ingesneden vleugelranden en een bonte onderkant.",
  "blauwe-morpho": "Blauwe morpho's lijken felblauw doordat microscopische structuren licht weerkaatsen.",
  "spinnendoder": "Spinnendoders verlammen spinnen om een voedselvoorraad voor hun larven aan te leggen.",
  "kameelspin": "Kameelspinnen zijn geen echte spinnen maar solifugen met krachtige kaken.",
  "hooiwagen": "Hooiwagens zijn spinachtigen met één compact lichaamsdeel en zeer lange poten.",
  "zweepspin": "Zweeppinnen gebruiken hun lange voorpoten als tastorganen in donkere schuilplaatsen.",
  "doorncicade": "Doorncicaden hebben een sterk verlengd halsschild dat op een doorn lijkt.",
  "kortschildkever": "Kortschildkevers hebben korte dekschilden waardoor een groot deel van hun achterlijf zichtbaar blijft.",
  "uilvlinder": "Veel uilvlinders zijn vooral in de avond en nacht actief en rusten overdag verborgen.",
  "groot-avondrood": "Het groot avondrood is een pijlstaartvlinder die in de schemering nectar zoekt.",
  "alpenboktor": "De alpenboktor heeft lange antennes en een blauwgrijs gevlekt patroon op zijn dekschilden.",
  "veenmol": "Veenmollen graven met brede voorpoten gangen in losse, vochtige grond.",
  "schietmot": "Schietmotlarven leven in water en bouwen beschermende huisjes van zand, takjes of bladeren.",
  "eendagsvlieg": "Volwassen eendagsvliegen leven vaak maar kort en eten dan nauwelijks of niet.",
  "oranjetipje": "Het mannetje van het oranjetipje heeft heldere oranje vlekken op de voorvleugels.",
  "kleine-vuurvlinder": "Kleine vuurvlinders hebben koperkleurige vleugels die in zonlicht sterk opvallen.",
  "dikkopje": "Dikkopjes hebben een stevig lichaam en rusten vaak met deels gespreide vleugels.",
  "veldkrekel": "Veldkrekels maken hun roepgeluid door de voorvleugels tegen elkaar te wrijven.",
  "coloradokever": "Coloradokevers hebben opvallende zwarte lengtestrepen en eten vooral bladeren van nachtschades.",
  "meeltor": "Meeltorlarven zijn bekend als meelwormen en leven van droge plantaardige resten.",
  "roodbruine-rijstmeelkever": "Roodbruine rijstmeelkevers komen voor in opgeslagen meel, granen en andere droge producten.",
  "schorskever": "Schorskevers leven onder boomschors waar ze gangpatronen in het bastweefsel maken.",
  "glimworm": "Glimwormen maken licht met een chemische reactie in hun achterlijf.",
  "zijdevlinder": "Zijdevlinders zijn bekend omdat hun rupsen lange draden zijde kunnen produceren.",
  "gevlekte-komkommerkever": "Gevlekte komkommerkevers hebben donkere stippen op gele dekschilden.",
  "gestreepte-komkommerkever": "Gestreepte komkommerkevers hebben drie donkere lengtestrepen op gele dekschilden.",
  "oliekever": "Oliekevers kunnen bij gevaar een olieachtige verdedigingsvloeistof afscheiden.",
  "groentje": "Het groentje is een kleine vlinder met een opvallend groene onderkant van de vleugels.",
  "heideblauwtje": "Heideblauwtjes leven op heide en de mannetjes tonen bovenop een heldere blauwe kleur.",
  "grote-weerschijnvlinder": "De grote weerschijnvlinder krijgt zijn blauwe glans door lichtbreking in de vleugelschubben.",
  "bruin-zandoogje": "Bruine zandoogjes hebben oogvlekken die roofdieren kunnen afleiden.",
  "kraamwebspin": "Kraamwebspinnen bewaken een eicocon en maken later een los web voor de jonge spinnen.",
  "groene-krabspin": "Groene krabspinnen wachten vaak roerloos op bloemen of bladeren tot prooi dichtbij komt.",
  "honingbij": "Honingbijen communiceren onder meer met een kwispeldans over voedselbronnen.",
  "dambordvlieg": "Dambordvliegen hebben vaak een zwartgrijs geblokt achterlijf dat aan een dambord doet denken.",
  "ligusterpijlstaart": "Ligusterpijlstaarten zijn grote nachtvlinders met een gestroomlijnd lichaam en smalle voorvleugels.",
  "dorbladbidsprinkhaan": "Dorbladbidsprinkhanen lijken door hun bruine vorm en aders sterk op droge bladeren.",
  "roze-sprinkhaan": "Roze sprinkhanen danken hun kleur aan een zeldzame pigmentafwijking, niet aan hun geslacht.",
  "gouden-vogelvlinder": "Gouden vogelvlinders hebben brede vleugels met een opvallend geelgroen patroon.",
  "pauwoogpijlstaart": "Pauwoogpijlstaarten kunnen hun achtervleugels tonen met oogvlekken om belagers te laten schrikken.",
  "smaragd-springspin": "Springspinnen besluipen prooi met scherpe ogen en maken korte, gerichte sprongen.",
  "broodkever": "Broodkevers leven van droge voorraadproducten en kunnen zich door dunne verpakkingen heen werken.",
  "gewone-houtwormkever": "De larven van gewone houtwormkevers knagen gangen in droog hout; de ronde gaatjes zijn hun uitvliegopeningen.",
  "gewone-kogelspin": "Gewone kogelspinnen maken een rommelig web in beschutte hoeken en hebben een kenmerkend bol achterlijf.",
  "kruipende-kogelspin": "Kruipende kogelspinnen leven vaak laag bij de grond en jagen vooral wanneer het donker is.",
  "nachtkaardespin": "Nachtkaardespinnen bouwen 's avonds een groot wielweb en zitten overdag meestal verborgen.",
  "argusvlinder": "Argusvlinders gebruiken hun vele oogvlekken om belagers te laten schrikken of af te leiden.",
  "spaanse-vlag": "De Spaanse vlag vliegt vaak overdag en toont bij het opvliegen plots haar felrode achtervleugels.",
  "weidebeekjuffer": "Weidebeekjuffers leven bij langzaam stromend, zuurstofrijk water met veel oeverplanten.",
  "steenhommel": "Steenhommels nestelen geregeld onder stenen en zijn herkenbaar aan hun oranjerode achterlijfspunt.",
  "aardhommel": "Aardhommels maken hun nest vaak in een verlaten muizenhol en kunnen daardoor onder de grond verdwijnen.",
  "akkerhommel": "Akkerhommels hebben meestal een warmbruine vacht en bezoeken heel veel verschillende soorten bloemen.",
  "boomhommel": "Boomhommels wonen graag bovengronds, bijvoorbeeld in een nestkast, dakrand of holle boom.",
  "heidehommel": "Heidehommels zoeken vooral lage bloemen af en kunnen hun nest tussen gras en mos bouwen.",
  "tuinhommel": "Tuinhommels hebben een uitzonderlijk lange tong waarmee ze nectar uit diepe bloemen kunnen halen.",
  "weidehommel": "Weidehommels behoren tot de eerste hommels van het jaar en vallen op door hun oranjerode staart.",
  "veldhommel": "Veldhommels lijken sterk op aardhommels, maar hun witte staart is de duidelijkste aanwijzing tijdens het zoeken.",
  "muskusboktor": "Muskusboktorren leven als larve in wilgenhout en kunnen een zachte muskusachtige geur verspreiden.",
  "eikenpage": "Eikenpages leven vooral hoog in eiken en komen daardoor minder vaak naar de grond.",
  ...bugDexExpansionFacts
};

const severityBase: Record<BugSeverity, number> = {
  Laag: 5,
  Normaal: 10,
  Hoog: 20,
  Kritiek: 35
};

export function calculateBugPoints(severity: BugSeverity, status: BugStatus): number {
  if (status === "Afgekeurd" || status === "Dubbel") {
    return 0;
  }
  if (status === "Gefixt") {
    return severityBase[severity] + 15;
  }
  if (status === "Bevestigd" || status === "In behandeling") {
    return severityBase[severity] + 5;
  }
  return severityBase[severity];
}

export function titleForPoints(points: number): string {
  return getTierForPoints(points).title;
}

export function getTierForPoints(points: number): UserTier {
  return [...userTiers].reverse().find((tier) => points >= tier.minPoints) ?? userTiers[0];
}

export function pointsUntilNextTier(points: number): number | null {
  const nextTier = userTiers.find((tier) => tier.minPoints > points);
  return nextTier ? nextTier.minPoints - points : null;
}

export type BadgeDefinition = {
  id: string;
  name: string;
  descriptionKey: string;
  bugDexSetId?: string;
  minBugDexCaught?: number;
  minBugReports?: number;
  minComments?: number;
  minLegendaryBugDex?: number;
  minMovementKm?: number;
  minMythicBugDex?: number;
  minPoints?: number;
  minSplats?: number;
  minTradedBugDex?: number;
  minUpgradedBugDex?: number;
  minUpvotesGiven?: number;
};

export const badgeDefinitions: BadgeDefinition[] = [
  { id: "first-catch", name: "Eerste vangst", descriptionKey: "badge.firstCatch.description", minBugReports: 1 },
  { id: "scout", name: "Speurneus", descriptionKey: "badge.scout.description", minBugReports: 5 },
  { id: "bugstorm", name: "Bugstorm", descriptionKey: "badge.bugstorm.description", minBugReports: 20 },
  { id: "bug-marathon", name: "Bugmarathon", descriptionKey: "badge.bugMarathon.description", minBugReports: 50 },
  { id: "points", name: "Puntenslijper", descriptionKey: "badge.points.description", minPoints: 100 },
  { id: "status", name: "Statusstrijder", descriptionKey: "badge.status.description", minPoints: 150 },
  { id: "colony", name: "Meesterkolonie", descriptionKey: "badge.colony.description", minPoints: 300 },
  { id: "walker", name: "Wandeljager", descriptionKey: "badge.walker.description", minMovementKm: 5 },
  { id: "kilometer-colony", name: "Kilometerkolonie", descriptionKey: "badge.kilometerColony.description", minMovementKm: 25 },
  { id: "marathon-hunter", name: "Marathonjager", descriptionKey: "badge.marathonHunter.description", minMovementKm: 100 },
  { id: "long-range-tracker", name: "Langeafstandsspeurder", descriptionKey: "badge.longRangeTracker.description", minMovementKm: 250 },
  { id: "bugdex-starter", name: "Dexstarter", descriptionKey: "badge.dexStarter.description", minBugDexCaught: 10 },
  { id: "dex-collector", name: "Dexverzamelaar", descriptionKey: "badge.dexCollector.description", minBugDexCaught: 50 },
  { id: "dex-master", name: "Dexmeester", descriptionKey: "badge.dexMaster.description", minBugDexCaught: 100 },
  { id: "legendary-catch", name: "Legendarische vangst", descriptionKey: "badge.legendaryCatch.description", minLegendaryBugDex: 1 },
  { id: "legendary-collector", name: "Legendarische collectie", descriptionKey: "badge.legendaryCollector.description", minLegendaryBugDex: 5 },
  { id: "mythic-catch", name: "Mythische vangst", descriptionKey: "badge.mythicCatch.description", minMythicBugDex: 1 },
  { id: "mythic-master", name: "Mythische meester", descriptionKey: "badge.mythicMaster.description", minMythicBugDex: 3 },
  { id: "bugdex-set-beetle-brigade", name: "Keverbende", descriptionKey: "badge.bugdexSet.description", bugDexSetId: "beetle_brigade" },
  { id: "bugdex-set-wings-of-color", name: "Vlinders & motten", descriptionKey: "badge.bugdexSet.description", bugDexSetId: "wings_of_color" },
  { id: "bugdex-set-buzz-squad", name: "Vliegers & muggen", descriptionKey: "badge.bugdexSet.description", bugDexSetId: "buzz_squad" },
  { id: "bugdex-set-sting-team", name: "Steekteam", descriptionKey: "badge.bugdexSet.description", bugDexSetId: "sting_team" },
  { id: "bugdex-set-pattern-warnings", name: "Wantsen & cicades", descriptionKey: "badge.bugdexSet.description", bugDexSetId: "pattern_warnings" },
  { id: "bugdex-set-web-and-sting", name: "Web & angel", descriptionKey: "badge.bugdexSet.description", bugDexSetId: "web_and_sting" },
  { id: "bugdex-set-jump-and-hide", name: "Springers & camo", descriptionKey: "badge.bugdexSet.description", bugDexSetId: "jump_and_hide" },
  { id: "bugdex-set-water-hunters", name: "Waterjagers", descriptionKey: "badge.bugdexSet.description", bugDexSetId: "water_hunters" },
  { id: "bugdex-set-house-raiders", name: "Huisplaagjes", descriptionKey: "badge.bugdexSet.description", bugDexSetId: "house_raiders" },
  { id: "bugdex-set-mythic-showcase", name: "Mythische vondsten", descriptionKey: "badge.bugdexSet.description", bugDexSetId: "mythic_showcase" },
  { id: "bugdex-set-night-crew", name: "Nachtbeesten", descriptionKey: "badge.bugdexSet.description", bugDexSetId: "night_crew" },
  { id: "trader", name: "Ruilkever", descriptionKey: "badge.trader.description", minTradedBugDex: 1 },
  { id: "upgrade-smith", name: "Upgrade-smid", descriptionKey: "badge.upgradeSmith.description", minUpgradedBugDex: 1 },
  { id: "splat-hunter", name: "Splatjager", descriptionKey: "badge.splatHunter.description", minSplats: 10 },
  { id: "comment-helper", name: "Reactiehelper", descriptionKey: "badge.commentHelper.description", minComments: 5 },
  { id: "discussion-pro", name: "Discussiepro", descriptionKey: "badge.discussionPro.description", minComments: 25 },
  { id: "upvote-ally", name: "Stemgenoot", descriptionKey: "badge.upvoteAlly.description", minUpvotesGiven: 10 }
];

export function badgesForUser(user: Partial<Pick<User,
  "bugCount" |
  "bugDexCount" |
  "commentPointCount" |
  "legendaryBugDexCount" |
  "movementKmTotal" |
  "mythicBugDexCount" |
  "splatCount" |
  "totalPoints" |
  "tradedBugDexCount" |
  "upvoteGivenPointCount" |
  "upgradedBugDexCount"
>>): string[] {
  return badgeDefinitions
    .filter((badge) =>
      badge.bugDexSetId === undefined &&
      (badge.minBugReports === undefined || (user.bugCount ?? 0) >= badge.minBugReports) &&
      (badge.minBugDexCaught === undefined || (user.bugDexCount ?? 0) >= badge.minBugDexCaught) &&
      (badge.minLegendaryBugDex === undefined || (user.legendaryBugDexCount ?? 0) >= badge.minLegendaryBugDex) &&
      (badge.minMovementKm === undefined || (user.movementKmTotal ?? 0) >= badge.minMovementKm) &&
      (badge.minMythicBugDex === undefined || (user.mythicBugDexCount ?? 0) >= badge.minMythicBugDex) &&
      (badge.minComments === undefined || (user.commentPointCount ?? 0) >= badge.minComments) &&
      (badge.minPoints === undefined || (user.totalPoints ?? 0) >= badge.minPoints) &&
      (badge.minSplats === undefined || (user.splatCount ?? 0) >= badge.minSplats) &&
      (badge.minTradedBugDex === undefined || (user.tradedBugDexCount ?? 0) >= badge.minTradedBugDex) &&
      (badge.minUpgradedBugDex === undefined || (user.upgradedBugDexCount ?? 0) >= badge.minUpgradedBugDex) &&
      (badge.minUpvotesGiven === undefined || (user.upvoteGivenPointCount ?? 0) >= badge.minUpvotesGiven)
    )
    .map((badge) => badge.name);
}

export function isBugDexEntryUnlocked(entry: BugDexEntry, user: Pick<User, "totalPoints" | "bugCount">): boolean {
  return (entry.unlockMode ?? "rank") === "rank" && user.totalPoints >= entry.minPoints && user.bugCount >= entry.minBugs;
}

export function unlockedBugDexCount(user: Pick<User, "totalPoints" | "bugCount">): number {
  return bugDexEntries.filter((entry) => isBugDexEntryUnlocked(entry, user)).length;
}
